
// Additional original full-case simulations for the CURRENT NCMHCE format.
// Each case: 3 narrative sections × 3 questions = 9 questions.
FULL_CASES.push(
{
 id:"elena-full", icon:"🚗", title:"Elena · Trauma After a Crash", focus:"Trauma · avoidance · grounding · treatment planning",
 client:{age:"34",sex:"Female",gender:"Cisgender female",pronouns:"She/her",orientation:"Heterosexual",race:"White",relationship:"Married",setting:"Private group practice",payment:"Insurance",type:"Individual",provisional:"Posttraumatic stress disorder (provisional)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Elena seeks counseling six months after a serious motor-vehicle crash in which she was trapped in her car until emergency crews arrived. Since then, she has nightmares, avoids highways, startles at screeching brakes, and becomes tense when riding as a passenger. She says she is embarrassed that she still reacts so strongly because the crash is “over.” She denies suicidal ideation and says she wants to drive to work independently again.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Assess trauma",q:"What additional information is MOST important for diagnostic assessment?",choices:["Only whether Elena likes driving","The full trauma-symptom pattern, duration, impairment, and rule-outs","Whether her spouse thinks she is overreacting","Her favorite route to work"],answer:1,why:"Trauma diagnosis depends on symptom clusters, duration, impairment, and appropriate differential assessment.",rule:"TRAUMA diagnosis = exposure + clusters + duration + impairment."},
    {domain:"Core Counseling Attributes",sub:"Empathic responding",q:"Which response BEST addresses Elena's embarrassment?",choices:["“You should be over it by now.”","“It makes sense that your body is still reacting after something terrifying, even though the danger has passed.”","“Try not to think about the crash.”","“At least you survived.”"],answer:1,why:"The response validates her experience without reinforcing helplessness or minimizing the trauma.",rule:"VALIDATE the response without validating avoidance."},
    {domain:"Treatment Planning",sub:"Establish goals",q:"Which initial treatment goal BEST reflects Elena's stated priorities?",choices:["Eliminate every anxious feeling","Gradually resume valued driving activities while reducing trauma-related avoidance and distress","Never ride in a car again","Focus only on childhood memories"],answer:1,why:"The goal is functional, client-centered, and related to the presenting problem.",rule:"GOAL = meaningful function, not zero emotion."}
   ]},
  {label:"Part Two",section:"Third counseling session · 3 weeks later",narrative:"Elena reports she can ride as a passenger on local roads but still avoids highways. During discussion of the crash, she suddenly looks distant, stops answering, and says the room feels far away. You notice she is staring at one spot and seems less oriented to the present moment.",
   questions:[
    {domain:"Counseling Skills & Interventions",sub:"Contain intense feelings",q:"What is the BEST immediate intervention?",choices:["Continue detailed trauma processing","Use grounding and orient Elena to the present environment","Challenge her thinking about the crash","End counseling permanently"],answer:1,why:"Dissociative symptoms call for stabilization and present-moment orientation before further processing.",rule:"DISSOCIATION → ground first."},
    {domain:"Counseling Skills & Interventions",sub:"Facilitate trust and safety",q:"What should the counselor communicate after Elena reorients?",choices:["That she failed the session","That the pace can be adjusted and she retains control over how trauma work proceeds","That trauma work always requires reliving every detail","That avoidance should be ignored"],answer:1,why:"Trauma-informed care emphasizes safety, collaboration, and pacing.",rule:"TRAUMA work = choice + pacing + safety."},
    {domain:"Treatment Planning",sub:"Revise treatment plan",q:"How should this session affect the treatment plan?",choices:["No change is ever needed","Include stabilization/grounding skills and adjust the pace of trauma processing","Discontinue all treatment","Remove the driving goal"],answer:1,why:"The plan should respond to the client's current tolerance and needs.",rule:"NEW clinical data → revise the plan."}
   ]},
  {label:"Part Three",section:"Tenth counseling session · 12 weeks after intake",narrative:"Elena reports she has driven several highway exits with a support person and later completed the route independently. Nightmares are less frequent. She still feels a surge of anxiety when she sees damaged vehicles but says, “I notice it, breathe, and keep going.” She wants to know whether she should continue therapy.",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which outcome BEST reflects meaningful progress?",choices:["No trauma reminders ever occur","She can notice trauma-related activation without automatically avoiding and has resumed valued activities","She depends on others for all driving","She refuses to discuss the crash"],answer:1,why:"Progress is reflected by reduced avoidance and improved functioning, even with some residual symptoms.",rule:"PROGRESS = function + flexibility."},
    {domain:"Treatment Planning",sub:"Termination",q:"What is the BEST next step?",choices:["End immediately without discussion","Review goals, residual symptoms, relapse-prevention skills, and readiness for planned termination","Continue indefinitely regardless of progress","Create a new unrelated diagnosis"],answer:1,why:"Termination should be collaborative and connected to goals and maintenance planning.",rule:"TERMINATION is a clinical task, not an abrupt stop."},
    {domain:"Counseling Skills & Interventions",sub:"Maintenance",q:"Which strategy BEST supports maintenance?",choices:["Avoid all highways again if anxiety returns","Continue using learned coping and approach behaviors when trauma cues arise","Seek reassurance after every trigger","Stop all skill practice"],answer:1,why:"Continued use of effective coping and approach behaviors supports long-term gains.",rule:"KEEP practicing what changed the pattern."}
   ]}
 ]},
{
 id:"jamal-full", icon:"🧩", title:"Jamal · First-Episode Psychosis?", focus:"Psychosis · differential · safety · coordination",
 client:{age:"20",sex:"Male",gender:"Cisgender male",pronouns:"He/him",orientation:"Heterosexual",race:"Black",relationship:"Single",setting:"University counseling center",payment:"Student services",type:"Individual",provisional:"Unspecified psychotic disorder (provisional)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Jamal is referred by a resident advisor after several weeks of social withdrawal and missed classes. He says he sometimes hears a voice commenting on what he is doing and believes people in the dorm may be talking about him through the walls. He appears guarded but cooperative. He denies suicidal or homicidal intent. He reports sleeping four to five hours nightly and says he has been using high-potency cannabis most evenings.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Differential diagnosis",q:"What assessment area is MOST important before determining a psychotic disorder diagnosis?",choices:["Only family income","Substance use, medical factors, mood symptoms, timeline, and functional decline","Favorite music","Whether Jamal likes his dorm"],answer:1,why:"Psychotic symptoms require differential assessment for substance-related, medical, mood-related, and primary psychotic conditions.",rule:"PSYCHOSIS symptom → build the differential."},
    {domain:"Intake, Assessment & Diagnosis",sub:"Mental Status Exam",q:"Jamal's belief that people talk about him through the walls is primarily documented under which MSE area?",choices:["Appearance","Thought content","Orientation","Memory"],answer:1,why:"Ideas such as paranoia or delusional beliefs are documented under thought content.",rule:"THOUGHT PROCESS = flow; THOUGHT CONTENT = what is believed."},
    {domain:"Core Counseling Attributes",sub:"Nonjudgmental stance",q:"Which counselor response is MOST appropriate?",choices:["“That is obviously not real.”","“Tell me more about what you notice and what it is like for you when that happens.”","“You need to stop talking about voices.”","“I believe the dorm is spying on you too.”"],answer:1,why:"The counselor can explore the experience without arguing with or validating the belief as fact.",rule:"EXPLORE experience without confirming the delusion."}
   ]},
  {label:"Part Two",section:"Second counseling session · 4 days later",narrative:"Jamal reports he stopped cannabis two days ago but still hears the voice. He slept only three hours last night and says the voice told him he is “weak,” but it has not told him to harm himself or others. He agrees to have his older sister join briefly by phone and says she has noticed he has become increasingly suspicious and isolated over the past month.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Risk assessment",q:"What should the counselor assess specifically regarding the voice?",choices:["Only volume","Content, commands, distress, control, associated risk, and Jamal's response to it","Whether his sister hears it too","Whether the voice is male or female only"],answer:1,why:"Command content, distress, behavioral influence, and safety implications matter clinically.",rule:"VOICE + RISK → assess what it says and what the client may do."},
    {domain:"Treatment Planning",sub:"Refer for concurrent treatment",q:"What is the BEST next care-planning step?",choices:["Counseling alone with no further evaluation","Coordinate an urgent psychiatric/medical evaluation while continuing supportive assessment as appropriate","Tell Jamal to wait several months","Assume cannabis fully explains the symptoms"],answer:1,why:"First-episode psychotic symptoms warrant timely evaluation and coordinated care.",rule:"FIRST EPISODE + functional decline → timely coordinated evaluation."},
    {domain:"Professional Practice & Ethics",sub:"Provide information to third parties",q:"If Jamal consents to coordination with his sister and a psychiatric provider, what is the BEST documentation practice?",choices:["Document authorization, relevant information shared, and the clinical reason for coordination","Do not document the contact","Share the full record automatically","Document only the sister's opinions"],answer:0,why:"Coordination should be documented clearly and limited to relevant information.",rule:"COORDINATION = permission + purpose + documentation."}
   ]},
  {label:"Part Three",section:"Sixth counseling session · 6 weeks after intake",narrative:"Jamal is now engaged with an early-psychosis specialty program and a psychiatrist. He reports improved sleep and fewer voices. He has reduced cannabis use substantially and returned to two classes. He remains worried that classmates may judge him if they learn he is receiving treatment.",
   questions:[
    {domain:"Treatment Planning",sub:"Collaborate with other providers",q:"Which counselor action BEST supports continuity of care?",choices:["Avoid all communication with the specialty team","With authorization, coordinate goals and clarify each provider's role","Duplicate every service","Tell Jamal to choose only one provider immediately"],answer:1,why:"Clear role coordination can reduce fragmentation and support continuity.",rule:"MULTIPLE PROVIDERS → clarify roles, don't create chaos."},
    {domain:"Counseling Skills & Interventions",sub:"Address stigma/support systems",q:"Which intervention BEST addresses Jamal's concern about judgment?",choices:["Tell him no one will judge him","Explore stigma concerns, identify supportive people, and help him decide what disclosure feels safe and useful","Require him to tell classmates","Avoid the topic"],answer:1,why:"The counselor supports autonomy, coping, and social support without making false assurances.",rule:"STIGMA work = validate + options + autonomy."},
    {domain:"Treatment Planning",sub:"Review goals",q:"What is the BEST indicator that treatment planning is working?",choices:["He has no symptoms at all","Improved functioning, engagement in coordinated care, reduced distress, and progress toward his own goals","He agrees with every provider","He never discusses cannabis"],answer:1,why:"Clinical progress includes functioning, engagement, symptom burden, safety, and client-defined goals.",rule:"PROGRESS is multidimensional."}
   ]}
 ]},
{
 id:"noah-full", icon:"🌀", title:"Noah · Obsessions & Checking", focus:"OCD · functional analysis · ERP",
 client:{age:"24",sex:"Male",gender:"Cisgender male",pronouns:"He/him",orientation:"Gay",race:"Asian American",relationship:"Single",setting:"Outpatient clinic",payment:"Insurance",type:"Individual",provisional:"Obsessive-compulsive disorder (provisional)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Noah reports repeated intrusive images that he might accidentally hit someone while driving. He says the thoughts are unwanted and disturbing. After driving, he often turns around several times to check the road and later searches local news for accidents. He knows the checking is excessive but says it briefly lowers his anxiety.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Determine diagnosis",q:"Which pattern is MOST consistent with Noah's presentation?",choices:["OCD-type obsessions and compulsions","Mania","Antisocial personality disorder","Delirium"],answer:0,why:"Intrusive unwanted thoughts plus repetitive checking that reduces distress fit an OCD pattern.",rule:"INTRUSION + ritualized neutralizing = OCD loop."},
    {domain:"Intake, Assessment & Diagnosis",sub:"Assess distress/functioning",q:"What additional information is MOST useful?",choices:["Time spent checking, avoidance, distress, insight, and impact on work/social functioning","His favorite car","Whether friends think the fear is logical","His shoe size"],answer:0,why:"Severity and impairment help determine clinical significance and treatment needs.",rule:"MEASURE the loop's cost."},
    {domain:"Core Counseling Attributes",sub:"Nonjudgmental stance",q:"Which response BEST supports rapport?",choices:["“That fear makes no sense.”","“You know the checking feels excessive, but it also gives you short-term relief from a terrifying possibility.”","“Just stop checking.”","“Maybe you really did hit someone.”"],answer:1,why:"The response reflects the function of the behavior without endorsing the feared belief.",rule:"UNDERSTAND the function before changing the behavior."}
   ]},
  {label:"Part Two",section:"Fourth counseling session · 4 weeks later",narrative:"Noah tracks his behavior and discovers he spends 90 minutes daily checking roads and news sites. He has begun avoiding driving at night. He says reassurance from friends helps for only a few minutes before doubt returns. You introduce the OCD cycle and discuss exposure and response prevention.",
   questions:[
    {domain:"Counseling Skills & Interventions",sub:"Theory-based intervention",q:"What is the purpose of response prevention?",choices:["Increase checking until it feels complete","Reduce ritualized behaviors that reinforce the obsession-anxiety cycle","Convince Noah the feared event is impossible","Teach distraction only"],answer:1,why:"Response prevention targets compulsive neutralizing that maintains the cycle.",rule:"ERP targets what keeps the loop alive."},
    {domain:"Treatment Planning",sub:"Establish objectives",q:"Which objective is MOST measurable?",choices:["Noah will feel less weird","Noah will complete three planned driving exposures this week while reducing post-drive checking","Noah will stop OCD immediately","Counselor will explain OCD"],answer:1,why:"The objective specifies a behavioral target linked to the treatment mechanism.",rule:"OBJECTIVE = observable client action."},
    {domain:"Counseling Skills & Interventions",sub:"Guide skills",q:"How should reassurance-seeking be addressed?",choices:["Provide unlimited reassurance","Collaboratively reduce reassurance-seeking because it may function like a compulsion","Ask friends to reassure Noah more strongly","Ignore the pattern"],answer:1,why:"Reassurance can become another neutralizing ritual that maintains OCD.",rule:"REASSURANCE can be a compulsion in disguise."}
   ]},
  {label:"Part Three",section:"Twelfth counseling session · 14 weeks after intake",narrative:"Noah reports he is driving at night again. He still has intrusive thoughts but no longer turns around to check most of the time. He says, “The thought can be there without me having to solve it.” His checking time has fallen from 90 minutes daily to about 10 minutes on difficult days.",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which change BEST reflects treatment progress?",choices:["The thoughts never occur","Noah can tolerate uncertainty with far less checking and has resumed driving","He asks for more reassurance","He avoids nighttime driving"],answer:1,why:"Reduced compulsions, improved functioning, and increased tolerance of uncertainty are meaningful outcomes.",rule:"OCD recovery ≠ never having intrusive thoughts."},
    {domain:"Counseling Skills & Interventions",sub:"Maintenance",q:"Which maintenance strategy is BEST?",choices:["Resume checking whenever anxiety rises","Continue planned exposure/response prevention and expect occasional intrusive thoughts","Avoid all triggers","Ask friends to monitor him"],answer:1,why:"Continued skills practice helps maintain learning and reduce relapse.",rule:"KEEP practicing approach + non-ritual response."},
    {domain:"Treatment Planning",sub:"Termination",q:"Before termination, what should Noah and the counselor review?",choices:["Only his initial diagnosis","Warning signs, high-risk situations for ritual return, strategies, supports, and how to re-enter care if needed","Nothing because he improved","A promise that OCD will never recur"],answer:1,why:"Relapse-prevention planning supports sustained gains.",rule:"ENDING = prepare for future bumps."}
   ]}
 ]},
{
 id:"ari-full", icon:"🎒", title:"Ari · Attention, Learning & School", focus:"Child assessment · ADHD differential · school collaboration",
 client:{age:"9",sex:"Male",gender:"Cisgender male",pronouns:"He/him",orientation:"N/A",race:"Multiracial",relationship:"N/A",setting:"School-linked outpatient program",payment:"Medicaid",type:"Individual/family",provisional:"Attention-deficit/hyperactivity disorder (rule out)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Ari is referred for incomplete work, frequent talking, leaving his seat, and difficulty following multistep directions. His parent reports similar distractibility at home and difficulty settling at bedtime. His teacher adds that reading assignments trigger the most frustration. Ari says, “The words get mixed up and then I get mad.”",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Biopsychosocial assessment",q:"What is the BEST assessment approach?",choices:["Diagnose ADHD from the referral alone","Gather information across home and school and assess developmental, learning, sleep, medical, emotional, and environmental factors","Use only Ari's self-report","Ignore the reading concern"],answer:1,why:"Child assessment benefits from multiple informants and attention to overlapping contributors.",rule:"KIDS live in systems → assess across settings."},
    {domain:"Intake, Assessment & Diagnosis",sub:"Assessment instruments",q:"Which principle should guide selection of an ADHD measure?",choices:["Use any child test","Use a validated measure appropriate to Ari's age and target symptoms, ideally with multi-informant data","Choose the longest measure","Use an adult personality inventory"],answer:1,why:"The instrument should fit the construct, age, purpose, and setting.",rule:"QUESTION → CONSTRUCT → TOOL."},
    {domain:"Treatment Planning",sub:"Identify strengths",q:"Which detail could be explored as a strength?",choices:["Ari can describe when reading becomes frustrating","He leaves his seat","He dislikes homework","His teacher is concerned"],answer:0,why:"Self-awareness about triggers can support collaborative strategies.",rule:"STRENGTHS include insight and usable skills."}
   ]},
  {label:"Part Two",section:"Team consultation · 3 weeks later",narrative:"Parent and teacher rating scales both show elevated attention and hyperactivity concerns. School data also show a marked reading-fluency delay. Ari sleeps about seven hours and often stays up with a tablet. Family history includes ADHD and dyslexia. The school team is considering a formal educational evaluation.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Co-occurring diagnoses",q:"What should remain part of the differential?",choices:["Possible ADHD plus learning and sleep-related contributors","Only ADHD because rating scales were elevated","Psychosis","No diagnosis can ever be considered"],answer:0,why:"The data support attention concerns while also pointing to learning and sleep factors that may contribute to impairment.",rule:"DO NOT let one positive screen close the differential."},
    {domain:"Treatment Planning",sub:"Collaborate with providers/support systems",q:"What is the BEST systems-level action?",choices:["Coordinate with the family and school around educational assessment and supports","Tell Ari to try harder","Avoid school collaboration","Wait until adulthood"],answer:0,why:"School collaboration can clarify learning needs and improve functional support.",rule:"INDIRECT care can be clinically essential."},
    {domain:"Counseling Skills & Interventions",sub:"Align intervention with developmental level",q:"Which intervention is MOST developmentally appropriate?",choices:["A 60-minute abstract lecture on executive function","Brief visual routines, concrete behavioral supports, parent/teacher collaboration, and skill practice","Complex psychodynamic interpretation only","No caregiver involvement ever"],answer:1,why:"Children often benefit from concrete, visual, behaviorally anchored interventions coordinated with caregivers/school.",rule:"MATCH intervention to developmental level."}
   ]},
  {label:"Part Three",section:"Eighth counseling session · 10 weeks after intake",narrative:"Ari now uses a visual homework routine and movement breaks. His parent reports fewer arguments at homework time. Educational testing identified a reading disorder, and the school added targeted reading supports. Ari still becomes impulsive during transitions but can name two strategies that help.",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which outcome BEST shows meaningful progress?",choices:["Ari never gets distracted","Family conflict is lower, supports are in place, and Ari can use strategies","He no longer needs reading support","The school stops documenting symptoms"],answer:1,why:"Progress can occur even when symptoms remain, especially when functioning and skill use improve.",rule:"PROGRESS = better function + skill use."},
    {domain:"Treatment Planning",sub:"Revise treatment plan",q:"How should the reading-disorder finding affect the plan?",choices:["Ignore it because counseling is only mental health","Integrate school supports into the broader plan and avoid attributing all academic difficulty to ADHD","Remove all ADHD goals","Tell the school to stop accommodations"],answer:1,why:"Updated assessment information should refine the formulation and coordination plan.",rule:"NEW assessment data → update the formulation."},
    {domain:"Core Counseling Attributes",sub:"Positive regard",q:"Ari says, “I'm the bad kid.” What response is BEST?",choices:["“Yes, your behavior is a problem.”","“You are having a hard time with some skills; that is different from being a bad kid.”","“Don't say that.”","“Your teacher made you feel that way.”"],answer:1,why:"The response separates the child from the behavior and supports a nonjudgmental stance.",rule:"PERSON ≠ problem behavior."}
   ]}
 ]},
{
 id:"nia-full", icon:"🌿", title:"Nia · Cannabis, Sleep & Ambivalence", focus:"Substance use · MI · scope · care coordination",
 client:{age:"29",sex:"Female",gender:"Cisgender female",pronouns:"She/her",orientation:"Bisexual",race:"Black",relationship:"Partnered",setting:"Community clinic",payment:"Insurance",type:"Individual",provisional:"Cannabis use disorder, mild (provisional)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Nia reports nightly cannabis use because it “turns my brain off.” Her partner complains that she is emotionally unavailable, and Nia has been late to work several times after using heavily the night before. Nia says, “I know it is causing problems, but I'm not promising I will quit forever.”",
   questions:[
    {domain:"Counseling Skills & Interventions",sub:"Facilitate motivation",q:"Which response BEST fits motivational interviewing?",choices:["“You have to stop now.”","“Part of you relies on cannabis for relief, and another part is noticing costs. What changes would feel worth trying?”","“Your partner is right.”","“Let's ignore cannabis.”"],answer:1,why:"MI reflects ambivalence and evokes client-defined reasons and next steps.",rule:"MI = evoke, don't lecture."},
    {domain:"Intake, Assessment & Diagnosis",sub:"Assess substance use",q:"What information is MOST important to assess?",choices:["Pattern, quantity, triggers, tolerance/withdrawal, consequences, attempts to cut down, and other substances","Favorite strain only","Whether her partner also uses","Only work attendance"],answer:0,why:"A substance-use assessment examines pattern, impairment, physiological features, consequences, and context.",rule:"SUBSTANCE assessment = pattern + function + consequences + physiology."},
    {domain:"Treatment Planning",sub:"Collaborative goals",q:"Which initial goal BEST matches Nia's readiness?",choices:["Permanent abstinence immediately whether she agrees or not","Track use, sleep, triggers, and work impact while identifying a realistic change target","Discharge her for ambivalence","Ask her partner to set the goal"],answer:1,why:"The plan should be collaborative and matched to readiness for change.",rule:"PLAN WITH the client, not at the client."}
   ]},
  {label:"Part Two",section:"Fourth counseling session · 4 weeks later",narrative:"Nia has reduced use from seven nights a week to three or four. She notices urges are strongest after conflict and on nights she expects poor sleep. She has had two nights of marked insomnia since cutting back and asks whether the counselor can recommend a specific prescription sleep medication.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Assess withdrawal/medical needs",q:"What is the BEST assessment response to the insomnia?",choices:["Assume it is unrelated","Clarify timing, severity, withdrawal effects, other causes, and whether medical evaluation is indicated","Tell her to resume nightly use","Diagnose bipolar disorder from insomnia alone"],answer:1,why:"Sleep changes after substance reduction should be assessed in context rather than assumed.",rule:"NEW symptom after behavior change? Check the timeline."},
    {domain:"Professional Practice & Ethics",sub:"Scope of practice",q:"How should the counselor respond to the medication request?",choices:["Recommend a prescription and dose","Stay within scope and refer/coordinate with an appropriate prescriber if Nia wants medication evaluation","Recommend a friend's medication","Ignore the question"],answer:1,why:"Counselors can address behavioral sleep strategies but do not prescribe medication outside scope.",rule:"STAY IN SCOPE; connect to the right provider."},
    {domain:"Counseling Skills & Interventions",sub:"Develop coping skills",q:"Which intervention BEST fits the identified trigger pattern?",choices:["Develop alternative responses for post-conflict distress and sleep-related anxiety","Tell her triggers do not matter","Increase use on stressful days","Focus only on childhood"],answer:0,why:"Identifying triggers and building alternative coping responses targets the function of use.",rule:"TRIGGER → function → alternative response."}
   ]},
  {label:"Part Three",section:"Tenth counseling session · 12 weeks after intake",narrative:"Nia reports cannabis use once or twice weekly, no recent work lateness, and improved communication with her partner. She met with a primary-care provider about sleep and is using a consistent sleep routine. She says, “I still like cannabis, but I don't feel like it runs my schedule anymore.”",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which change BEST reflects progress?",choices:["She has not committed to lifetime abstinence","Use and consequences have decreased, functioning improved, and she reports greater choice","She still likes cannabis","Her partner still has opinions"],answer:1,why:"Progress can be measured by reduced harm, improved functioning, goal attainment, and increased self-efficacy.",rule:"CHANGE is measured against goals and impairment, not ideology."},
    {domain:"Core Counseling Attributes",sub:"Positive regard",q:"Which response BEST fits a nonjudgmental stance?",choices:["“You should still feel guilty.”","“You are noticing more choice in how and when you use, and that matters to you.”","“You failed because you did not quit.”","“Your partner should decide whether this is enough.”"],answer:1,why:"The counselor reflects the client's progress without imposing a moral judgment.",rule:"NONJUDGMENTAL ≠ uncritical; it means respectful."},
    {domain:"Treatment Planning",sub:"Maintenance",q:"What should be included in maintenance planning?",choices:["High-risk triggers, coping options, sleep supports, and a plan for what to do if use or consequences increase","A promise to never experience an urge","Only a discharge date","No plan because she improved"],answer:0,why:"Maintenance planning helps the client respond early if old patterns return.",rule:"MAINTENANCE = know your warning signs + next moves."}
   ]}
 ]},
{
 id:"priya-full", icon:"🌙", title:"Priya · Grief, Culture & Depression", focus:"Grief · cultural formulation · differential · intervention",
 client:{age:"52",sex:"Female",gender:"Cisgender female",pronouns:"She/her",orientation:"Heterosexual",race:"South Asian",relationship:"Widowed",setting:"Hospital outpatient clinic",payment:"Insurance",type:"Individual",provisional:"Bereavement-related distress; rule out major depressive disorder"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Priya seeks counseling four months after her husband's death. She reports frequent crying, loneliness, difficulty sleeping, and guilt that she did not recognize his medical decline sooner. She remains involved with family and continues working part-time but says evenings feel unbearable. She finds comfort in religious rituals and visits with her sister.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Cultural formulation",q:"What is the BEST approach to Priya's religious and cultural practices?",choices:["Assume their meaning","Ask how the practices function for her and whether they are sources of support, conflict, or both","Avoid discussing them","Explain the counselor's beliefs"],answer:1,why:"Cultural formulation explores the client's meaning rather than imposing assumptions.",rule:"CULTURE → ask meaning, don't assign meaning."},
    {domain:"Intake, Assessment & Diagnosis",sub:"Differential diagnosis",q:"What information is MOST important for distinguishing grief from a depressive disorder?",choices:["Only time since death","Symptom pattern, pervasive anhedonia/hopelessness, self-worth, functioning, suicidality, and course over time","Whether friends think she is grieving too long","Her age alone"],answer:1,why:"Grief and depression can overlap; the full symptom pattern, course, and impairment matter.",rule:"DIFFERENTIAL = pattern, not one symptom."},
    {domain:"Core Counseling Attributes",sub:"Empathic attunement",q:"Which response BEST fits Priya's guilt?",choices:["“You could not have known.”","“You keep replaying what you wish you had noticed, and it sounds painful to carry that responsibility now.”","“Stop blaming yourself.”","“Your husband would not want this.”"],answer:1,why:"The response reflects the emotional meaning without prematurely reassuring or speaking for the deceased.",rule:"REFLECT before reassuring."}
   ]},
  {label:"Part Two",section:"Fifth counseling session · 6 weeks later",narrative:"Priya reports she is sleeping somewhat better and has resumed weekly family dinners. She still avoids the bedroom she shared with her husband and spends evenings on the couch. She says entering the bedroom makes the loss feel “too real.” She also worries that family members expect her to grieve differently than she does.",
   questions:[
    {domain:"Counseling Skills & Interventions",sub:"Address cultural considerations",q:"What is the BEST counseling response to family expectations?",choices:["Tell Priya which cultural tradition is correct","Explore the meaning of family expectations and support Priya in identifying what fits her own values and needs","Tell her culture should not matter","Call her relatives without permission"],answer:1,why:"Culturally responsive counseling explores context while preserving client agency.",rule:"CULTURE + AUTONOMY can coexist."},
    {domain:"Treatment Planning",sub:"Identify barriers",q:"How might bedroom avoidance be conceptualized in planning?",choices:["As a potential avoidance pattern that may maintain distress and interfere with valued functioning","As proof of psychosis","As irrelevant","As a moral failure"],answer:0,why:"Avoidance can maintain distress and can be explored collaboratively when clinically appropriate.",rule:"ASK what avoidance protects—and what it costs."},
    {domain:"Counseling Skills & Interventions",sub:"Theory-based intervention",q:"Which intervention direction is MOST appropriate?",choices:["Collaboratively approach avoided reminders at a tolerable pace while processing grief and meaning","Force Priya to sleep in the bedroom tonight","Tell her to move immediately","Avoid grief reminders permanently"],answer:0,why:"A paced, collaborative approach can reduce avoidance while respecting grief and readiness.",rule:"APPROACH gradually; don't coerce."}
   ]},
  {label:"Part Three",section:"Twelfth counseling session · 4 months later",narrative:"Priya now sleeps in the bedroom several nights each week and says she can remember her husband with both sadness and warmth. She remains connected to family, work, and religious community. She still has difficult anniversary days but says, “I do not feel stuck every day anymore.”",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which statement BEST reflects progress?",choices:["She never feels grief","She can experience grief while remaining connected to valued roles and activities","She avoids all reminders","She stopped talking about her husband"],answer:1,why:"Adaptive grief can continue while functioning and flexibility improve.",rule:"HEALING ≠ forgetting or never feeling sad."},
    {domain:"Core Counseling Attributes",sub:"Positive regard",q:"Which counselor stance is MOST appropriate toward anniversary distress?",choices:["Treat it as treatment failure","Normalize that grief can fluctuate around meaningful dates while assessing any clinically significant worsening","Tell Priya to distract herself","Assume relapse"],answer:1,why:"Fluctuating grief responses can occur without negating progress.",rule:"CONTEXT matters when symptoms change."},
    {domain:"Treatment Planning",sub:"Termination",q:"What is the BEST termination focus?",choices:["Review supports, coping around future anniversaries, and how she will recognize if she wants to return","Promise grief is over","End without discussing support","Tell family to monitor her"],answer:0,why:"Planned termination supports continued adaptation and clear pathways back to care.",rule:"PLAN for predictable hard days."}
   ]}
 ]},
{
 id:"samantha-full", icon:"🍽️", title:"Samantha · Eating, Control & Medical Risk", focus:"Eating disorder · medical stability · level of care",
 client:{age:"19",sex:"Female",gender:"Cisgender female",pronouns:"She/her",orientation:"Heterosexual",race:"White",relationship:"Single",setting:"College counseling center",payment:"Student services",type:"Individual",provisional:"Other specified feeding or eating disorder (provisional)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Samantha reports increasing restriction over six months, intense fear of weight gain, and rigid food rules. She says she often skips breakfast and lunch, then exercises late at night. She reports dizziness when standing and one fainting episode last week. She says, “I am not thin enough for this to be serious.”",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Determine level of care",q:"What is the clinical priority?",choices:["Body-image journaling only","Prompt medical evaluation for potential instability while continuing mental health assessment","Wait until her weight changes more","Focus only on self-esteem"],answer:1,why:"Dizziness and fainting in the context of restriction can indicate medical risk requiring evaluation.",rule:"MEDICAL INSTABILITY beats outpatient homework."},
    {domain:"Core Counseling Attributes",sub:"Nonjudgmental stance",q:"Which response BEST addresses Samantha's statement that she is “not thin enough” for concern?",choices:["“You are right.”","“Medical risk is not determined by appearance alone, and your fainting and restriction deserve careful assessment.”","“You look fine to me.”","“You need to gain weight immediately.”"],answer:1,why:"The response corrects a dangerous misconception without shaming or focusing on appearance.",rule:"APPEARANCE does not determine severity."},
    {domain:"Intake, Assessment & Diagnosis",sub:"Assessment",q:"Which additional information is MOST important?",choices:["Eating pattern, compensatory behaviors, weight/medical changes, exercise, body-image concerns, substances, mood, and safety","Favorite foods only","Social media use only","Roommate opinions only"],answer:0,why:"A comprehensive eating-disorder assessment includes behaviors, medical risk, cognition, mood, and functional impact.",rule:"EATING assessment = behavior + body + medical + mood + function."}
   ]},
  {label:"Part Two",section:"Care coordination · 1 week later",narrative:"A medical provider identifies orthostatic changes and recommends close medical monitoring. Samantha agrees to meet with a dietitian and specialized eating-disorder clinician. She tells you she is embarrassed and fears losing control if treatment asks her to change eating patterns.",
   questions:[
    {domain:"Treatment Planning",sub:"Collaborate with providers",q:"What is the BEST counseling role now?",choices:["Act as the only provider","Coordinate with the interdisciplinary team within scope and authorization, while supporting Samantha's engagement and goals","Tell the dietitian how to prescribe meals","Ignore medical recommendations"],answer:1,why:"Eating-disorder care often requires coordinated interdisciplinary treatment.",rule:"COMPLEX risk → coordinated care."},
    {domain:"Counseling Skills & Interventions",sub:"Facilitate motivation",q:"Which response BEST fits Samantha's fear of losing control?",choices:["“You have to surrender control.”","“Part of the restriction may feel like control, and treatment feels threatening because it asks you to do something different. Can we look at both the protection and the cost?”","“That fear is irrational.”","“Do whatever the dietitian says.”"],answer:1,why:"Exploring ambivalence can support engagement without coercion.",rule:"AMBIVALENCE is information, not defiance."},
    {domain:"Professional Practice & Ethics",sub:"Competence",q:"If the counselor lacks specialized eating-disorder training, what is the BEST response?",choices:["Provide specialized treatment anyway","Use supervision/consultation and refer or coordinate for specialized care while staying within competence","Hide the limitation","End all counseling support automatically"],answer:1,why:"Competence requires appropriate training, consultation, and referral when needed.",rule:"KNOW your lane—and build a team."}
   ]},
  {label:"Part Three",section:"Tenth counseling session · 3 months later",narrative:"Samantha remains in coordinated care. She reports fewer faint feelings, more consistent nutrition, and reduced compulsive exercise. She still experiences strong body-image distress before social events but can use coping skills without skipping meals most of the time.",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which outcome BEST reflects progress?",choices:["She likes her body every day","Medical symptoms, restrictive behavior, and compulsive exercise have decreased while skill use increased","She never has body-image distress","She avoids all social events"],answer:1,why:"Progress includes improved safety, behavior, functioning, and coping—not complete absence of distress.",rule:"TRACK behavior + function + safety."},
    {domain:"Counseling Skills & Interventions",sub:"Develop coping skills",q:"Which next intervention target is MOST appropriate?",choices:["Build coping for high-risk body-image situations while continuing team recommendations","Stop medical monitoring","Encourage meal skipping before events","End all support"],answer:0,why:"The plan should address residual triggers while maintaining safety and coordinated care.",rule:"TARGET the remaining high-risk pattern."},
    {domain:"Treatment Planning",sub:"Continuity of care",q:"What should be considered before reducing service intensity?",choices:["Only Samantha's preference","Medical stability, behavioral progress, coping, support, team input, and relapse risk","Whether school is on break","Whether she is tired of appointments"],answer:1,why:"Step-down decisions should integrate safety, functioning, and team assessment.",rule:"STEP-DOWN = clinical readiness, not calendar convenience."}
   ]}
 ]},
{
 id:"theo-full", icon:"💭", title:"Theo · Worry, Sleep & Overthinking", focus:"GAD · sleep · CBT · treatment planning",
 client:{age:"38",sex:"Male",gender:"Cisgender male",pronouns:"He/him",orientation:"Heterosexual",race:"White",relationship:"Married",setting:"Telehealth outpatient",payment:"Insurance",type:"Individual",provisional:"Generalized anxiety disorder (provisional)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Theo reports excessive worry about finances, work mistakes, his children's safety, and his health. He says the worry is difficult to control and has occurred most days for about eight months. He feels restless, irritable, tense, and has trouble sleeping. His primary-care provider recently ruled out a thyroid problem.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Determine diagnosis",q:"Which diagnosis is MOST consistent with the information provided?",choices:["Generalized anxiety disorder","Panic disorder","Specific phobia","Acute stress disorder"],answer:0,why:"The pattern involves excessive difficult-to-control worry across domains for more than six months with associated symptoms.",rule:"GAD = broad worry + difficult control + duration + associated symptoms."},
    {domain:"Intake, Assessment & Diagnosis",sub:"Assess functioning",q:"What is MOST important to assess next?",choices:["How worry affects sleep, work, relationships, decision-making, and daily functioning","His favorite news source","Whether coworkers worry too","Only childhood history"],answer:0,why:"Functional impact helps determine severity and treatment targets.",rule:"SYMPTOMS matter because of what they do to life."},
    {domain:"Treatment Planning",sub:"Collaborative goals",q:"Which goal is MOST appropriate?",choices:["Never worry again","Improve ability to manage worry and sleep while reducing interference with work and family life","Quit his job immediately","Avoid finances"],answer:1,why:"The goal is functional, realistic, and client-centered.",rule:"GOAL = meaningful improvement, not impossible certainty."}
   ]},
  {label:"Part Two",section:"Fourth counseling session · 4 weeks later",narrative:"Theo completes a worry log and notices he spends hours trying to mentally solve unlikely future problems. He checks work email repeatedly at night “just in case.” You introduce CBT strategies and a scheduled worry period.",
   questions:[
    {domain:"Counseling Skills & Interventions",sub:"Apply CBT",q:"Which intervention BEST fits the pattern?",choices:["Examine probability and coping estimates, reduce reassurance/checking, and test alternative responses","Tell Theo nothing bad will happen","Encourage more checking","Avoid discussing thoughts"],answer:0,why:"CBT can target catastrophic predictions and safety behaviors that maintain worry.",rule:"WORRY loop = prediction + checking + temporary relief."},
    {domain:"Counseling Skills & Interventions",sub:"Psychoeducation",q:"What is the purpose of a scheduled worry period?",choices:["To eliminate all thoughts","To contain and observe worry rather than responding to it continuously throughout the day","To increase rumination","To avoid sleep"],answer:1,why:"Scheduled worry can reduce all-day engagement with worry and increase intentional control over attention.",rule:"CONTAIN worry instead of letting it own the whole day."},
    {domain:"Treatment Planning",sub:"Identify barriers",q:"Theo's repeated nighttime email checking is best conceptualized as:",choices:["A behavior that may reinforce anxiety and disrupt sleep","Proof of psychosis","A strength only","An irrelevant work habit"],answer:0,why:"Checking can function as a safety behavior that temporarily reduces uncertainty while maintaining the cycle.",rule:"WHAT gives short-term relief may keep long-term anxiety alive."}
   ]},
  {label:"Part Three",section:"Eleventh counseling session · 12 weeks later",narrative:"Theo reports checking work email only once in the evening, sleeping more consistently, and spending more time with his family. Worry still spikes before major presentations, but he uses breathing, cognitive restructuring, and a written coping plan.",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which outcome BEST reflects meaningful progress?",choices:["Theo never worries","Worry is less impairing, checking is reduced, sleep improved, and coping increased","He avoids presentations","His family monitors him"],answer:1,why:"Improved functioning and reduced maintenance behaviors are key indicators of progress.",rule:"PROGRESS = less interference + more skillful response."},
    {domain:"Core Counseling Attributes",sub:"Positive regard",q:"Theo says, “I still get anxious before presentations, so maybe therapy didn't work.” Which response is BEST?",choices:["“Correct, anxiety means failure.”","“The goal was not zero anxiety; you've changed how much it controls your behavior and recovery.”","“You should cancel presentations.”","“Ignore the anxiety.”"],answer:1,why:"The response reframes progress in functional terms without minimizing the remaining anxiety.",rule:"SUCCESS ≠ zero symptoms."},
    {domain:"Treatment Planning",sub:"Maintenance",q:"What should Theo include in a relapse-prevention plan?",choices:["Early warning signs, checking patterns, sleep changes, coping strategies, and when to seek support","A guarantee he will never worry","More work email alerts","No plan"],answer:0,why:"Early recognition and planned responses support maintenance.",rule:"CATCH the old loop early."}
   ]}
 ]},
{
 id:"marisol-full", icon:"🏠", title:"Marisol · Partner Conflict & Safety", focus:"Relationship violence · safety assessment · boundaries",
 client:{age:"31",sex:"Female",gender:"Cisgender female",pronouns:"She/her",orientation:"Heterosexual",race:"Latina",relationship:"Married",setting:"Community agency",payment:"Sliding scale",type:"Individual",provisional:"Adjustment disorder with mixed anxiety and depressed mood (provisional)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Marisol seeks counseling for anxiety and low mood related to escalating conflict with her spouse. She says arguments have become more intense, and last week her spouse blocked the doorway when she tried to leave and punched a wall. Marisol says, “He has never hit me, so I don't know if it counts as abuse.”",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Assess relationship violence",q:"What should the counselor do FIRST?",choices:["Begin couples communication training","Conduct a focused safety and relationship-violence assessment","Tell Marisol to leave immediately","Minimize the event because she was not hit"],answer:1,why:"Coercive or threatening behavior warrants safety assessment before routine relationship interventions.",rule:"POSSIBLE IPV → assess safety before couples work."},
    {domain:"Core Counseling Attributes",sub:"Nonjudgmental stance",q:"Which response is BEST?",choices:["“It only counts if he hits you.”","“Blocking your exit and punching a wall can be frightening and controlling. I want to understand how safe you feel and what has been happening.”","“You should have left.”","“All couples fight.”"],answer:1,why:"The response names concern without blaming or dictating a decision.",rule:"VALIDATE risk without taking over the client's choices."},
    {domain:"Treatment Planning",sub:"Identify barriers/supports",q:"Which planning area is MOST important early on?",choices:["Safety resources, support network, transportation, finances, children if relevant, and options Marisol wants to consider","Career testing","Dream interpretation","Vacation planning"],answer:0,why:"Practical resources and supports can affect safety and options.",rule:"SAFETY planning includes real-world barriers."}
   ]},
  {label:"Part Two",section:"Third counseling session · 3 weeks later",narrative:"Marisol reports her spouse has apologized but now checks her phone frequently and becomes angry when she spends time with friends. She says she is not ready to leave the relationship. She agrees to identify two people she could call and a place she could go if she felt unsafe.",
   questions:[
    {domain:"Counseling Skills & Interventions",sub:"Develop safety plans",q:"What is the BEST counseling stance?",choices:["Refuse to continue unless she leaves","Collaboratively support safety planning and autonomy while continuing to assess risk","Tell her spouse about the safety plan","Begin conjoint therapy immediately"],answer:1,why:"Safety planning can occur even when the client is not ready to leave.",rule:"SAFETY + AUTONOMY, not coercion."},
    {domain:"Professional Practice & Ethics",sub:"Confidentiality",q:"If Marisol's spouse calls demanding information, what should the counselor generally do?",choices:["Disclose to reduce conflict","Maintain confidentiality unless Marisol authorizes disclosure or another legal exception applies","Confirm attendance only","Send the safety plan"],answer:1,why:"The spouse is not automatically entitled to information about individual counseling.",rule:"RELATIONSHIP status does not erase confidentiality."},
    {domain:"Counseling Skills & Interventions",sub:"Appropriate modality",q:"Why might conjoint couples counseling be inappropriate at this stage?",choices:["Couples counseling is never useful","Active coercive control or safety concerns can make conjoint work unsafe or clinically inappropriate","Marisol is anxious","The counselor prefers individual work"],answer:1,why:"When coercion or violence is present, safety and appropriateness of conjoint work must be carefully assessed.",rule:"MODALITY must fit safety conditions."}
   ]},
  {label:"Part Three",section:"Ninth counseling session · 3 months later",narrative:"Marisol reports she has strengthened contact with friends and family, has copies of important documents stored safely, and has a clearer plan if conflict escalates. She says the relationship remains uncertain but she feels “less trapped and more able to make decisions.”",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which change BEST represents progress?",choices:["Her spouse never gets angry","Marisol has increased safety options, support, and decision-making agency","She has made the exact decision the counselor prefers","She avoids all friends"],answer:1,why:"Increased safety, support, and autonomy are meaningful outcomes.",rule:"PROGRESS may be more options, not one prescribed decision."},
    {domain:"Core Counseling Attributes",sub:"Positive regard",q:"Which response BEST supports autonomy?",choices:["“Now you need to leave.”","“You have built more options and support; you get to decide what next step fits your safety and values.”","“Your family should decide.”","“If you stay, therapy failed.”"],answer:1,why:"The counselor supports informed client decision-making without coercion.",rule:"AUTONOMY remains central."},
    {domain:"Treatment Planning",sub:"Maintenance",q:"What should continue to be reviewed?",choices:["Safety indicators, support access, changing risk, and practical options","Only mood symptoms","Only relationship satisfaction","Nothing because the plan exists"],answer:0,why:"Relationship risk can change over time and requires ongoing reassessment.",rule:"SAFETY plans are living plans."}
   ]}
 ]},
{
 id:"omar-full", icon:"🌐", title:"Omar · Cultural Adjustment & Anxiety", focus:"Cultural formulation · anxiety · identity · support",
 client:{age:"27",sex:"Male",gender:"Cisgender male",pronouns:"He/him",orientation:"Heterosexual",race:"Middle Eastern",relationship:"Engaged",setting:"Community clinic",payment:"Insurance",type:"Individual",provisional:"Adjustment disorder with anxiety (provisional)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Omar moved to the United States eight months ago for graduate school. He reports persistent worry about speaking English in class, disappointing his family, and being judged because of his accent. He has begun skipping social events and feels isolated. He says his faith and weekly calls with family are important sources of support.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Cultural formulation",q:"What is the BEST assessment stance?",choices:["Assume anxiety is caused only by culture","Explore migration stress, discrimination, language demands, family expectations, identity, supports, and symptom pattern","Avoid culture entirely","Assume his family is the problem"],answer:1,why:"Cultural formulation considers context and meaning without reducing the client to culture.",rule:"CONTEXT matters without becoming the whole diagnosis."},
    {domain:"Core Counseling Attributes",sub:"Multicultural sensitivity",q:"Which response BEST demonstrates cultural humility?",choices:["“I know exactly how immigration feels.”","“I want to understand what these changes and expectations mean in your life, and I may need you to help me understand parts of your experience.”","“Culture is not relevant to anxiety.”","“Your family expectations are unhealthy.”"],answer:1,why:"Cultural humility acknowledges limits and centers the client's experience.",rule:"HUMILITY = curiosity + awareness of your limits."},
    {domain:"Treatment Planning",sub:"Identify strengths",q:"Which factors are clear strengths?",choices:["Faith, family connection, academic goals, and help-seeking","Avoiding social events","Fear of judgment","Skipping class discussions"],answer:0,why:"Existing supports and motivation can be integrated into treatment.",rule:"STRENGTHS can be cultural, relational, spiritual, and practical."}
   ]},
  {label:"Part Two",section:"Fifth counseling session · 6 weeks later",narrative:"Omar reports he now attends one campus organization and has met another student from his home region. He still experiences anxiety before presentations and sometimes interprets classmates' neutral expressions as criticism. You have been using CBT and gradual behavioral experiments.",
   questions:[
    {domain:"Counseling Skills & Interventions",sub:"Apply theory-based intervention",q:"Which CBT intervention BEST fits the presentation anxiety?",choices:["Identify predictions, test them through graded presentations, and review what actually happens","Tell Omar no one judges accents","Avoid presentations","Ask family to do presentations for him"],answer:0,why:"Behavioral experiments and cognitive review test feared predictions in real situations.",rule:"PREDICTION → experiment → evidence."},
    {domain:"Counseling Skills & Interventions",sub:"Address social support",q:"How should the new campus connection be used clinically?",choices:["Ignore it","Explore whether it provides belonging, practical support, and opportunities for valued engagement","Require the friendship","Replace all counseling with the friendship"],answer:1,why:"Social support can be a protective factor and treatment resource.",rule:"SUPPORT systems are part of treatment."},
    {domain:"Core Counseling Attributes",sub:"Nonjudgmental stance",q:"Omar worries that family expectations are “too much” but also says they give him purpose. What is the BEST stance?",choices:["Tell him to reject family expectations","Explore both the burden and meaning without forcing a Western individualistic interpretation","Tell him family always knows best","Avoid the topic"],answer:1,why:"Counseling should hold complexity rather than impose a single cultural value system.",rule:"BOTH/AND beats cultural assumptions."}
   ]},
  {label:"Part Three",section:"Twelfth counseling session · 4 months after intake",narrative:"Omar reports he is participating in class, attending campus events, and feels less isolated. He still experiences anxiety before major presentations but says it no longer determines whether he participates. He plans to travel home during break and wants to continue practicing skills independently.",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which outcome BEST reflects progress?",choices:["No anxiety ever","Participation and connection increased despite residual anxiety","He stopped speaking with family","He avoids all presentations"],answer:1,why:"Improved functioning and valued action can occur even when some anxiety remains.",rule:"FUNCTION beats symptom perfection."},
    {domain:"Treatment Planning",sub:"Maintenance",q:"What should a maintenance plan include?",choices:["Upcoming stressors, supports, presentation coping, behavioral practice, and warning signs of renewed avoidance","A promise to never feel anxious","Cutting off family","No plan"],answer:0,why:"Maintenance planning anticipates predictable stress and preserves effective strategies.",rule:"PLAN for predictable pressure points."},
    {domain:"Core Counseling Attributes",sub:"Respect for diversity",q:"How should the counselor approach Omar's return home?",choices:["Assume it will be stressful","Ask what he anticipates culturally, relationally, and emotionally and what support would be useful","Tell him not to go","Tell him how to behave with family"],answer:1,why:"The counselor remains curious and client-centered rather than presumptive.",rule:"ASK before interpreting."}
   ]}
 ]},
{
 id:"bree-full", icon:"🔥", title:"Bree · Emotion Dysregulation & Self-Harm", focus:"Self-harm · DBT skills · safety · boundaries",
 client:{age:"26",sex:"Female",gender:"Cisgender female",pronouns:"She/her",orientation:"Bisexual",race:"White",relationship:"Single",setting:"Community outpatient clinic",payment:"Insurance",type:"Individual",provisional:"Borderline personality disorder (provisional)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Bree reports intense mood shifts, fear of abandonment, unstable relationships, and a history of cutting when overwhelmed. She says she cut superficially two nights ago after an argument but denies current suicidal intent or plan. She describes cutting as “the fastest way to shut everything down.”",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Ongoing risk assessment",q:"What should the counselor assess NEXT?",choices:["Only whether the cuts required stitches","Suicidal intent, self-harm function, medical severity, triggers, history, access to means, protective factors, and current safety","Whether Bree regrets the argument","Only diagnosis criteria"],answer:1,why:"Nonsuicidal self-injury and suicide risk overlap but are not identical; both need direct assessment.",rule:"SELF-HARM → assess function AND suicide risk."},
    {domain:"Counseling Skills & Interventions",sub:"Crisis intervention",q:"Which early intervention is MOST appropriate if Bree can remain outpatient safely?",choices:["Build a collaborative safety/crisis plan and teach concrete distress-tolerance options","Ignore cutting because it was superficial","Require a promise she will never self-harm","Begin deep trauma processing immediately"],answer:0,why:"Immediate treatment should address safety and alternatives to high-risk coping.",rule:"LIFE-THREATENING / HIGH-RISK behaviors come first."},
    {domain:"Core Counseling Attributes",sub:"Nonjudgmental stance",q:"Which response BEST supports disclosure?",choices:["“Cutting is manipulative.”","“It sounds like cutting has functioned as a rapid way to reduce unbearable emotion, and we need safer ways to get you through those moments.”","“You know better.”","“Just stop.”"],answer:1,why:"The counselor identifies function without shaming and redirects toward safety.",rule:"UNDERSTAND function without endorsing harm."}
   ]},
  {label:"Part Two",section:"Fifth counseling session · 5 weeks later",narrative:"Bree has used ice, paced breathing, and calling a friend instead of cutting during two crises, but she did cut once after believing a date was going to reject her. She says, “If someone leaves, it proves I am impossible to love.”",
   questions:[
    {domain:"Counseling Skills & Interventions",sub:"DBT-informed skills",q:"Which intervention BEST fits the immediate treatment target?",choices:["Continue distress-tolerance/emotion-regulation practice and analyze the chain leading to self-harm","Only interpret childhood dreams","Stop discussing self-harm","Ask the date to attend therapy"],answer:0,why:"Behavior chain analysis and skills practice can identify links and alternatives around high-risk behavior.",rule:"CHAIN: trigger → thoughts/feelings → urges → behavior → consequence."},
    {domain:"Treatment Planning",sub:"Review progress",q:"How should the single recurrence be understood?",choices:["Treatment failed completely","As important clinical data to analyze while also recognizing increased use of safer coping","As proof Bree cannot improve","As irrelevant"],answer:1,why:"A recurrence does not erase progress and can guide plan refinement.",rule:"LAPSE = data, not destiny."},
    {domain:"Core Counseling Attributes",sub:"Empathic responding",q:"Which response BEST addresses “impossible to love”?",choices:["“That is dramatic.”","“When you sense someone pulling away, it seems to hit a deep fear that you are fundamentally unlovable.”","“You need better dating choices.”","“You are obviously lovable.”"],answer:1,why:"The response reflects the emotional meaning without dismissing or over-reassuring.",rule:"REFLECT the schema before challenging it."}
   ]},
  {label:"Part Three",section:"Fourteenth counseling session · 4 months after intake",narrative:"Bree reports no cutting for seven weeks and says she can usually identify escalation earlier. She still has intense abandonment fears but uses coping skills and reaches out to supports before crises peak. She asks whether she should continue weekly sessions.",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which factor BEST supports a step-down discussion?",choices:["No self-harm for seven weeks plus stronger early-warning recognition and skill use, considered alongside overall risk and functioning","The calendar alone","Bree is tired of therapy","The counselor needs an opening"],answer:0,why:"Service intensity should reflect risk, functioning, gains, and support—not convenience alone.",rule:"STEP-DOWN follows clinical readiness."},
    {domain:"Treatment Planning",sub:"Maintenance",q:"Which maintenance focus is MOST important?",choices:["Early warning signs, high-risk relationship triggers, crisis skills, supports, and when to increase care","A promise that abandonment fears will disappear","No plan because she improved","Avoiding relationships"],answer:0,why:"Relapse-prevention planning should target the known chain and supports.",rule:"PLAN around known triggers."},
    {domain:"Professional Practice & Ethics",sub:"Boundaries",q:"Bree asks whether she can text the counselor's personal number whenever she feels abandoned. What is the BEST response?",choices:["Give unrestricted personal access","Maintain communication boundaries, review crisis procedures, and explore the need behind the request","Block Bree without discussion","End therapy"],answer:1,why:"The counselor can validate the need while maintaining clear professional boundaries and crisis options.",rule:"BOUNDARY + safety plan + therapeutic exploration."}
   ]}
 ]},
{
 id:"lucas-full", icon:"👥", title:"Lucas · Group Anxiety & Belonging", focus:"Group counseling · social anxiety · group process",
 client:{age:"23",sex:"Male",gender:"Cisgender male",pronouns:"He/him",orientation:"Heterosexual",race:"White",relationship:"Single",setting:"University counseling center",payment:"Student services",type:"Group counseling",provisional:"Social anxiety disorder"},
 parts:[
  {label:"Part One",section:"Group intake",narrative:"Lucas is referred to an interpersonal process group because of social anxiety and isolation. In the pre-group meeting, he says he wants friends but fears saying something stupid. He asks whether group members are “allowed to talk about each other outside the room.”",
   questions:[
    {domain:"Professional Practice & Ethics",sub:"Group rules/confidentiality",q:"What should the counselor explain?",choices:["The leader can guarantee every member's confidentiality","Group expectations and confidentiality should be reviewed, including the limits of what the counselor can guarantee about other members","Members may post about sessions if names are omitted","Confidentiality does not apply to groups"],answer:1,why:"Leaders establish confidentiality expectations but cannot guarantee another member's behavior.",rule:"GROUP confidentiality has expectations AND limits."},
    {domain:"Treatment Planning",sub:"Appropriate modality",q:"Why might group be clinically useful for Lucas?",choices:["It provides live interpersonal practice and feedback in a structured setting","It guarantees he will make friends","It avoids all social exposure","It requires less counselor skill"],answer:0,why:"Group can offer in-vivo interpersonal learning and corrective experiences.",rule:"GROUP = live relational laboratory."},
    {domain:"Core Counseling Attributes",sub:"Foster group factors",q:"Which leader stance is MOST helpful early in group?",choices:["Demand immediate deep disclosure","Build safety, norms, universality, and connection gradually","Remain silent regardless of confusion","Encourage members to compete"],answer:1,why:"Early group stages benefit from structure, safety, and cohesion.",rule:"EARLY GROUP = safety + structure + belonging."}
   ]},
  {label:"Part Two",section:"Fourth group session",narrative:"Lucas rarely speaks unless called on. Another member says, “I notice you look like you want to say something and then disappear.” Lucas blushes and says, “I assume everyone here is judging me.” The group becomes quiet.",
   questions:[
    {domain:"Counseling Skills & Interventions",sub:"Here-and-now interaction",q:"What is the BEST leader move?",choices:["Change topics","Invite Lucas to notice what is happening in the room right now and, with consent, explore members' reactions","Tell Lucas his assumption is irrational","Ask him to leave"],answer:1,why:"Here-and-now work can make the interpersonal pattern visible and workable.",rule:"GROUP PROCESS lives in the room."},
    {domain:"Counseling Skills & Interventions",sub:"Linking",q:"Another member says, “I do the exact same thing.” What leader skill is MOST relevant?",choices:["Linking members around a shared theme","Blocking all discussion","Interpreting dreams","Changing the subject"],answer:0,why:"Linking can build universality and cohesion by connecting similar experiences.",rule:"LINK similarities to build group learning."},
    {domain:"Core Counseling Attributes",sub:"Conflict tolerance",q:"If a member responds, “Sometimes I do judge people,” what should the leader do?",choices:["Shut the member down immediately","Contain the tension and help the group explore impact, honesty, safety, and meaning","End group","Take sides"],answer:1,why:"The leader can tolerate and structure difficult interpersonal material without allowing harm.",rule:"CONTAIN conflict; don't fear it or let it run wild."}
   ]},
  {label:"Part Three",section:"Tenth group session",narrative:"Lucas now initiates comments and has met two group members for coffee after following the group's stated policy about outside contact. He reports joining a campus club and says, “I still get nervous, but I can survive being seen.”",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which outcome BEST reflects progress?",choices:["Lucas never feels anxiety","He participates, tolerates vulnerability, and engages socially despite anxiety","He becomes the most talkative member","He avoids feedback"],answer:1,why:"Functional engagement despite residual anxiety is a meaningful outcome.",rule:"FUNCTION > symptom perfection."},
    {domain:"Counseling Skills & Interventions",sub:"Group themes",q:"What theme could the leader highlight?",choices:["Movement from hiding toward tolerating visibility and connection","That anxiety is gone","That everyone should socialize outside group","That Lucas is cured"],answer:0,why:"Naming an emerging theme can consolidate learning across the group.",rule:"GROUP THEMES help members see the pattern."},
    {domain:"Treatment Planning",sub:"Group termination",q:"As group approaches ending, what should the leader address?",choices:["Reactions to ending, gains, unfinished work, supports, and how members will carry learning forward","Avoid termination discussion","Add new members without explanation","End by email only"],answer:0,why:"Termination is a meaningful phase of group process and should be addressed directly.",rule:"GROUP ENDING is part of the work."}
   ]}
 ]},
{
 id:"keisha-full", icon:"🧠", title:"Keisha · Depression, Career & Identity", focus:"Depression · career loss · CBT · strengths",
 client:{age:"45",sex:"Female",gender:"Cisgender female",pronouns:"She/her",orientation:"Heterosexual",race:"Black",relationship:"Married",setting:"Employee assistance program",payment:"Employer benefit",type:"Individual",provisional:"Major depressive disorder, single episode, moderate"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Keisha was laid off from a management role three months ago after 18 years with the same company. She reports depressed mood, loss of interest, guilt, low energy, oversleeping, and thoughts that she has “nothing useful to offer anymore.” She has stopped networking because she expects rejection. She denies suicidal ideation.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Determine diagnosis",q:"Which feature MOST supports a depressive disorder rather than normal disappointment alone?",choices:["Job loss","A sustained cluster of mood, cognitive, neurovegetative, and functional symptoms","Being married","Disliking networking"],answer:1,why:"Diagnosis depends on the symptom cluster, duration, and impairment—not the stressor alone.",rule:"STRESSOR ≠ diagnosis by itself."},
    {domain:"Treatment Planning",sub:"Identify strengths",q:"Which strength should be explored?",choices:["Eighteen years of work experience and prior leadership success","Oversleeping","Avoiding networking","Guilt"],answer:0,why:"Past functioning and competencies can support realistic goal development.",rule:"PAST effectiveness can be present strength."},
    {domain:"Core Counseling Attributes",sub:"Empathic responding",q:"Which response BEST fits “nothing useful to offer”?",choices:["“That is not true.”","“Losing a role that carried so much of your identity seems to have shaken how you see your value.”","“You just need a new job.”","“At least your spouse works.”"],answer:1,why:"The response reflects identity loss and emotional meaning without minimizing.",rule:"REFLECT meaning, not just event."}
   ]},
  {label:"Part Two",section:"Fourth counseling session · 4 weeks later",narrative:"Keisha identifies a pattern of all-or-nothing thinking: if she does not obtain a role equal to her old one, she sees herself as a failure. She completes two informational interviews but dismisses them because they did not lead immediately to job offers.",
   questions:[
    {domain:"Counseling Skills & Interventions",sub:"CBT",q:"Which intervention BEST fits?",choices:["Examine the all-or-nothing rule and redefine success in smaller, testable steps","Tell Keisha she is wrong","Stop discussing work","Only teach breathing"],answer:0,why:"CBT can target rigid beliefs and support graded behavioral activation.",rule:"CBT = test the rule + change behavior."},
    {domain:"Treatment Planning",sub:"Objectives",q:"Which objective is MOST measurable?",choices:["Feel successful","Complete two networking or application actions per week and rate mood/avoidance before and after","Get any job tomorrow","Counselor will motivate her"],answer:1,why:"The objective is specific, measurable, and behaviorally linked to the goal.",rule:"OBJECTIVE = specific client action."},
    {domain:"Counseling Skills & Interventions",sub:"Career development",q:"How can career counseling be integrated?",choices:["Explore transferable skills, values, role identity, and realistic options alongside mood treatment","Tell her to accept the first job offered","Avoid career issues because they are not mental health","Only administer a test"],answer:0,why:"Career and identity concerns can be directly relevant to clinical distress and recovery.",rule:"CAREER can be part of the clinical formulation."}
   ]},
  {label:"Part Three",section:"Tenth counseling session · 12 weeks after intake",narrative:"Keisha reports improved mood and energy. She has expanded her job search beyond identical management roles and accepted a temporary consulting project. She says, “I still want a leadership job, but this no longer feels like proof that I failed.”",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"What change BEST reflects progress?",choices:["She abandoned leadership goals","She has more flexible self-evaluation, resumed activity, and improved functioning","She stopped caring about work","She avoids applications"],answer:1,why:"Improved cognitive flexibility and behavioral engagement are meaningful treatment gains.",rule:"PROGRESS can be flexibility + action."},
    {domain:"Core Counseling Attributes",sub:"Positive regard",q:"Which response BEST supports agency?",choices:["“The consulting role fixed you.”","“You created more options without giving up what matters to you.”","“You should stay a consultant forever.”","“Leadership is too stressful.”"],answer:1,why:"The response highlights client agency and values without directing career choices.",rule:"HIGHLIGHT agency, not counselor ownership."},
    {domain:"Treatment Planning",sub:"Termination",q:"What should be reviewed before ending?",choices:["Relapse signs, coping, career stressors, supports, and how she will respond if avoidance increases","Only the job search","Nothing because mood improved","A promise never to feel rejected"],answer:0,why:"Maintenance planning connects remaining life stressors with learned skills.",rule:"PLAN for the trigger that started the cycle."}
   ]}
 ]},
{
 id:"daniel-full", icon:"🩺", title:"Daniel · Health Anxiety & Reassurance", focus:"Health anxiety · differential · CBT · medical coordination",
 client:{age:"36",sex:"Male",gender:"Cisgender male",pronouns:"He/him",orientation:"Heterosexual",race:"White",relationship:"Married",setting:"Integrated primary care",payment:"Insurance",type:"Individual",provisional:"Illness anxiety disorder (provisional)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Daniel reports persistent fear that ordinary bodily sensations signal serious illness. Over the past year he has visited urgent care repeatedly, searched symptoms online for hours, and asked his spouse to check his pulse. Multiple medical evaluations have been reassuring. He says the relief lasts only briefly.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Differential assessment",q:"What is important before finalizing a diagnosis?",choices:["Confirm relevant medical evaluation, symptom course, reassurance-seeking, functional impact, and other anxiety/OCD features","Assume all symptoms are psychological","Tell him to stop seeing physicians","Ask only about childhood"],answer:0,why:"Health anxiety diagnosis requires appropriate medical context and differential assessment.",rule:"DO NOT psychologize before considering medical context."},
    {domain:"Counseling Skills & Interventions",sub:"Functional analysis",q:"What behavior may be maintaining the cycle?",choices:["Repeated checking and reassurance-seeking","Going to work","Sleeping","Talking to his spouse generally"],answer:0,why:"Checking and reassurance often produce short-term relief that reinforces the cycle.",rule:"SHORT-TERM relief can maintain long-term anxiety."},
    {domain:"Core Counseling Attributes",sub:"Empathic responding",q:"Which response is BEST?",choices:["“Nothing is wrong with you.”","“The uncertainty feels so intolerable that checking gives you temporary relief, even though the fear quickly comes back.”","“You are wasting doctors' time.”","“Your spouse should stop helping.”"],answer:1,why:"The response captures the function of the behavior without shaming.",rule:"UNDERSTAND the loop before changing it."}
   ]},
  {label:"Part Two",section:"Fifth counseling session · 6 weeks later",narrative:"Daniel tracks checking and notices he searches symptoms online 15–20 times a day. He agrees to gradually reduce checking and delay reassurance requests. He worries that reducing checking could cause him to miss a real medical emergency.",
   questions:[
    {domain:"Counseling Skills & Interventions",sub:"CBT",q:"Which intervention BEST fits?",choices:["Create a collaborative plan to reduce checking while defining appropriate medical red flags with his healthcare provider","Tell him to ignore every symptom","Provide unlimited reassurance","Require him to stop medical care"],answer:0,why:"Treatment can reduce compulsive reassurance while preserving appropriate medical safety.",rule:"REDUCE excessive checking without dismissing real medical needs."},
    {domain:"Treatment Planning",sub:"Collaborate with providers",q:"Why is coordination with primary care useful?",choices:["To create a consistent approach to medical concerns and reduce fragmented reassurance-seeking","To convince the physician anxiety is fake","To transfer all therapy to the physician","To avoid documenting symptoms"],answer:0,why:"Integrated communication can support consistency and appropriate boundaries around medical evaluation.",rule:"COORDINATION reduces mixed messages."},
    {domain:"Treatment Planning",sub:"Objectives",q:"Which objective is MOST measurable?",choices:["Daniel will worry less","Daniel will reduce symptom searches from 15–20 daily to no more than 5 for two weeks while tracking anxiety","Daniel will never seek medical care","Counselor will reassure him"],answer:1,why:"The objective specifies a target behavior, baseline, and timeframe.",rule:"MEASURE the maintenance behavior."}
   ]},
  {label:"Part Three",section:"Twelfth counseling session · 4 months after intake",narrative:"Daniel reports he rarely searches symptoms online and no longer asks his spouse to check his pulse. He still notices health fears but can usually wait and follow the agreed medical plan rather than seeking immediate reassurance.",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which outcome BEST demonstrates progress?",choices:["No bodily sensations occur","Reassurance/checking decreased and Daniel can tolerate uncertainty while using appropriate medical guidance","He avoids all doctors","His spouse monitors him"],answer:1,why:"Reduced safety behaviors and increased tolerance of uncertainty reflect meaningful change.",rule:"PROGRESS = new response to uncertainty."},
    {domain:"Counseling Skills & Interventions",sub:"Maintenance",q:"What is the BEST maintenance strategy?",choices:["Resume checking during stressful weeks","Continue using the medical plan, delay reassurance, and notice urges without automatically acting","Ask spouse to take over checking","Avoid health information forever"],answer:1,why:"Maintenance preserves the new learning and appropriate medical boundaries.",rule:"URGE ≠ action."},
    {domain:"Core Counseling Attributes",sub:"Genuineness",q:"Daniel asks, “Can you promise I will never miss something serious?” What is the BEST response?",choices:["Promise absolute certainty","Acknowledge that certainty is impossible while reinforcing the agreed plan for appropriate medical concerns","Tell him he is being irrational","Change topics"],answer:1,why:"The counselor remains honest and avoids feeding reassurance dependence.",rule:"DO NOT sell certainty you cannot provide."}
   ]}
 ]},
{
 id:"tasha-full", icon:"🌧️", title:"Tasha · Postpartum Mood & Support", focus:"Perinatal mood · safety · support · coordination",
 client:{age:"32",sex:"Female",gender:"Cisgender female",pronouns:"She/her",orientation:"Heterosexual",race:"Black",relationship:"Married",setting:"Integrated women's health clinic",payment:"Insurance",type:"Individual",provisional:"Major depressive disorder with peripartum onset (provisional)"},
 parts:[
  {label:"Part One",section:"Intake",narrative:"Tasha is eight weeks postpartum and reports persistent sadness, guilt, low appetite, difficulty sleeping even when the baby sleeps, and feeling disconnected from activities she used to enjoy. She says, “A good mother should be happy. I feel like I am failing.” She denies intent to harm herself or the baby but says she sometimes wishes she could disappear.",
   questions:[
    {domain:"Intake, Assessment & Diagnosis",sub:"Risk assessment",q:"What should the counselor do NEXT?",choices:["Assume this is normal postpartum stress","Assess suicide risk directly and assess thoughts of harm to the baby, psychosis, supports, and ability to care safely","Tell her she should be grateful","Avoid safety questions"],answer:1,why:"Perinatal depression with passive death wishes warrants direct safety assessment and screening for other high-risk features.",rule:"POSTPARTUM + hopelessness → assess safety comprehensively."},
    {domain:"Core Counseling Attributes",sub:"Empathic responding",q:"Which response BEST addresses “a good mother should be happy”?",choices:["“You should be happy.”","“You are holding yourself to an impossible standard while also feeling depleted and disconnected.”","“All mothers feel this way.”","“Try to focus on the baby.”"],answer:1,why:"The response reflects self-judgment and emotional burden without minimizing.",rule:"VALIDATE distress; don't romanticize motherhood."},
    {domain:"Treatment Planning",sub:"Identify supports",q:"Which support area should be explored early?",choices:["Practical caregiving help, sleep opportunities, partner/family support, medical care, and trusted contacts","Only exercise","Only social media","No support because she is an adult"],answer:0,why:"Perinatal treatment planning should consider practical and relational supports alongside clinical care.",rule:"SUPPORT can be an intervention target."}
   ]},
  {label:"Part Two",section:"Third counseling session · 3 weeks later",narrative:"Tasha's obstetric provider has evaluated her and started treatment. Her spouse now covers one overnight feeding so Tasha can get a longer sleep block. She reports fewer passive death wishes but persistent guilt and isolation. She says she avoids telling friends because she is ashamed.",
   questions:[
    {domain:"Treatment Planning",sub:"Collaborate with providers",q:"What is the BEST counseling action?",choices:["Coordinate with the medical provider as authorized and continue monitoring symptoms/risk","Tell Tasha to stop medical treatment","Avoid communication because it is not counseling","Assume medication alone is enough"],answer:0,why:"Coordinated perinatal care supports continuity and safety.",rule:"MULTIMODAL care needs coordination."},
    {domain:"Counseling Skills & Interventions",sub:"Address support systems",q:"Which intervention BEST addresses isolation?",choices:["Explore shame, identify safe support options, and help Tasha choose gradual connection steps","Force her to tell everyone","Tell her isolation is irrational","Ignore social support"],answer:0,why:"Support-building should be collaborative and sensitive to shame.",rule:"CONNECTION is built, not prescribed."},
    {domain:"Counseling Skills & Interventions",sub:"CBT",q:"Which CBT target fits “A good mother should be happy all the time”?",choices:["Examine rigid standards and evidence for a more balanced belief","Agree with the rule","Avoid the thought","Ask spouse to challenge it"],answer:0,why:"CBT can address perfectionistic and self-critical beliefs contributing to depression.",rule:"RIGID SHOULD statements are CBT targets."}
   ]},
  {label:"Part Three",section:"Tenth counseling session · 3 months later",narrative:"Tasha reports improved mood, more consistent sleep, and stronger connection with the baby and spouse. She has resumed brief walks with a friend and attends a parent support group. She still has occasional guilt when she needs help but says she can challenge the belief that asking for help makes her inadequate.",
   questions:[
    {domain:"Treatment Planning",sub:"Review progress",q:"Which outcome BEST reflects progress?",choices:["Tasha never feels guilt","Mood, sleep, support, functioning, and self-compassion have improved","She no longer needs anyone","She stopped discussing parenting"],answer:1,why:"Progress is multidimensional and includes improved functioning and support.",rule:"TRACK the whole clinical picture."},
    {domain:"Treatment Planning",sub:"Maintenance",q:"Which maintenance plan is MOST appropriate?",choices:["Monitor sleep loss, isolation, hopelessness, and support needs; keep crisis and medical follow-up plans clear","Assume recurrence is impossible","Stop all support","Avoid discussing future stress"],answer:0,why:"Known warning signs and coordinated supports should remain part of maintenance planning.",rule:"KNOW the early warning signs."},
    {domain:"Core Counseling Attributes",sub:"Positive regard",q:"Tasha says, “I still need help sometimes.” Which response BEST supports growth?",choices:["“Then you are not recovered.”","“Needing help and using support can be part of healthy functioning, not evidence of failure.”","“Try to stop needing anyone.”","“Your spouse should do more.”"],answer:1,why:"The response challenges shame while respecting interdependence.",rule:"INDEPENDENCE is not the only measure of health."}
   ]}
 ]}
);