const DOMAINS = [
  "Professional Practice & Ethics",
  "Intake, Assessment & Diagnosis",
  "Treatment Planning",
  "Counseling Skills & Interventions",
  "Core Counseling Attributes",
  "Areas of Clinical Focus"
];

const VISUAL_RULES = [
  "FIRST? → Safety before sophistication.",
  "ATTACK = episode. DISORDER = pattern + duration + impairment.",
  "GOAL = destination. OBJECTIVE = measurable step. INTERVENTION = what you do.",
  "ASSESS before you ASSUME.",
  "Match the TOOL to the QUESTION you are trying to answer.",
  "BEST answer = clinically useful + ethically sound + least assumptive.",
  "Do not diagnose from one symptom. Build the pattern.",
  "Client autonomy stays central unless safety or law clearly changes the frame.",
  "When two answers sound therapeutic, pick the one that fits THIS moment.",
  "New information can change the best answer. Read the timeline."
];

const QUESTIONS = [
{id:1,domain:"Professional Practice & Ethics",topic:"Informed consent",difficulty:1,profiles:["current","2027"],q:"At the first session, which item belongs in informed consent?",stem:"A client asks what they should know before deciding whether to begin counseling.",choices:["The counselor's political beliefs","Fees, limits of confidentiality, and relevant risks/benefits","A guarantee that counseling will work","The names of the counselor's other clients"],answer:1,why:"Informed consent includes information needed for an informed choice, including fees, limits of confidentiality, and relevant risks/benefits.",rule:"INFORMED CONSENT = enough information to choose freely."},
{id:2,domain:"Professional Practice & Ethics",topic:"Competence",difficulty:2,profiles:["current","2027"],q:"A counselor receives a referral for a specialized treatment they have never been trained to provide. What is the BEST next step?",choices:["Accept and learn as you go without telling the client","Assess competence, seek appropriate consultation/training, and refer if needed","Decline every client with that diagnosis","Ask the client to choose the treatment method"],answer:1,why:"Counselors evaluate their competence and use supervision, consultation, training, or referral when needed.",rule:"COMPETENCE first; confidence is not competence."},
{id:3,domain:"Professional Practice & Ethics",topic:"Confidentiality",difficulty:2,profiles:["current","2027"],q:"A client's employer calls requesting confirmation that the client attends therapy. What should the counselor generally do FIRST?",choices:["Confirm attendance only","Decline to disclose without authorization or another valid legal basis","Send the entire record","Ask the employer why they want the information and then disclose"],answer:1,why:"Even confirming treatment can disclose protected information. Authorization or another valid basis is needed.",rule:"Even YES/NO can be a disclosure."},
{id:4,domain:"Professional Practice & Ethics",topic:"Records",difficulty:2,profiles:["current","2027"],q:"Which documentation style is most defensible?",choices:["Objective, clinically relevant, timely, and limited to necessary information","Detailed personal opinions about the client","Only positive information","No documentation when the session is routine"],answer:0,why:"Clinical records should be timely, accurate, relevant, and professional.",rule:"DOCUMENT facts + clinical reasoning, not frustration."},
{id:5,domain:"Professional Practice & Ethics",topic:"Boundaries",difficulty:3,profiles:["current","2027"],q:"A client sends a social media friend request to the counselor's personal account. What is the BEST response?",choices:["Accept to strengthen rapport","Ignore it forever and never discuss it","Maintain the boundary and discuss the request and social media policy in session","Create a fake account to follow the client instead"],answer:2,why:"The counselor should maintain appropriate boundaries and address the meaning/policy transparently.",rule:"BOUNDARY + PROCESS beats silent weirdness."},
{id:6,domain:"Professional Practice & Ethics",topic:"Supervision",difficulty:2,profiles:["current","2027"],q:"A trainee is unsure whether a case exceeds their competence. What action is MOST appropriate?",choices:["Hide the uncertainty","Seek supervision promptly","Terminate immediately without consultation","Ask another client what they think"],answer:1,why:"Supervision is the appropriate resource for clinical uncertainty and scope questions.",rule:"UNCERTAIN + TRAINEE → supervision."},

{id:7,domain:"Intake, Assessment & Diagnosis",topic:"MSE",difficulty:1,profiles:["current","2027"],q:"Which finding belongs in a Mental Status Examination?",choices:["Housing history","Appearance, behavior, mood, thought process, cognition, insight, judgment","Three-generation genogram","Insurance deductible"],answer:1,why:"An MSE is a structured snapshot of current mental functioning.",rule:"MSE = what is happening NOW in mental functioning."},
{id:8,domain:"Intake, Assessment & Diagnosis",topic:"Suicide risk",difficulty:2,profiles:["current","2027"],q:"A client says, “Sometimes I wish I wouldn't wake up.” What should the counselor do NEXT?",choices:["Change the subject to avoid increasing risk","Directly assess suicidal thoughts, intent, plan, means, history, and protective factors","Immediately diagnose major depression","Promise to keep everything secret"],answer:1,why:"Passive death wishes require direct, calm risk assessment before deciding level of response.",rule:"HINT OF SUICIDE → assess, don't guess."},
{id:9,domain:"Intake, Assessment & Diagnosis",topic:"Panic",difficulty:2,profiles:["current","2027"],q:"A client reports one abrupt episode of intense fear with pounding heart, trembling, dizziness, and shortness of breath. Which is the safest conclusion from this information alone?",choices:["Panic disorder","A panic attack occurred","Generalized anxiety disorder","Agoraphobia"],answer:1,why:"A single episode can meet criteria for a panic attack; panic disorder requires a broader pattern.",rule:"ATTACK = event. DISORDER = pattern."},
{id:10,domain:"Intake, Assessment & Diagnosis",topic:"Differential",difficulty:3,profiles:["current","2027"],q:"A client presents with new-onset anxiety, tremor, sweating, and rapid heartbeat. What should the counselor consider during assessment?",choices:["Only psychological causes","Possible medical and substance-related contributors","That the client is exaggerating","That anxiety always means trauma"],answer:1,why:"Differential assessment includes medical, substance, medication, and psychiatric explanations when indicated.",rule:"NEW physical symptoms? Rule out medical/substance contributors."},
{id:11,domain:"Intake, Assessment & Diagnosis",topic:"Assessment tool",difficulty:2,profiles:["current","2027"],q:"What is the BEST principle for choosing an assessment instrument?",choices:["Use the longest test available","Match the instrument to the construct, population, purpose, and counselor competence","Use whichever test is free","Use the same test for every diagnosis"],answer:1,why:"Assessment selection should fit the referral question, population, psychometrics, purpose, and administrator competence.",rule:"QUESTION → CONSTRUCT → TOOL."},
{id:12,domain:"Intake, Assessment & Diagnosis",topic:"Bipolar differential",difficulty:3,profiles:["current","2027"],q:"Before diagnosing unipolar depression, which history is especially important to explore?",choices:["Favorite foods","Past periods of elevated/irritable mood with increased energy and decreased need for sleep","Whether the client owns a pet","Handedness"],answer:1,why:"A history of mania or hypomania can change the diagnostic picture substantially.",rule:"DEPRESSION? Always scan for past mania/hypomania."},
{id:13,domain:"Intake, Assessment & Diagnosis",topic:"Trauma",difficulty:2,profiles:["current","2027"],q:"Which approach is most appropriate when screening for trauma?",choices:["Demand a detailed trauma narrative immediately","Use a paced, respectful assessment and avoid unnecessary detail before safety/rapport","Assume everyone with anxiety has PTSD","Avoid trauma questions entirely"],answer:1,why:"Trauma-informed assessment balances necessary information with safety, pacing, and client control.",rule:"TRAUMA ASSESSMENT = enough to guide care, not forced disclosure."},
{id:14,domain:"Intake, Assessment & Diagnosis",topic:"Substance use",difficulty:2,profiles:["current","2027"],q:"A client has mood symptoms and heavy substance use. What is the BEST assessment stance?",choices:["Assume the mood symptoms are primary","Assume substances explain everything","Clarify timing, pattern, intoxication/withdrawal effects, and periods of abstinence","Refuse to assess until the client is abstinent for a year"],answer:2,why:"Timing and symptom course help distinguish primary, substance-induced, and co-occurring conditions.",rule:"TIMELINE is your differential diagnosis superpower."},

{id:15,domain:"Treatment Planning",topic:"Goals",difficulty:1,profiles:["current","2027"],q:"Which statement is MOST like a treatment goal?",choices:["Counselor will teach diaphragmatic breathing","Client will improve ability to manage panic symptoms and resume avoided activities","Client will complete a worksheet tonight","Counselor will review psychoeducation"],answer:1,why:"Goals describe desired client outcomes; interventions describe clinician actions; objectives are measurable steps.",rule:"GOAL = destination."},
{id:16,domain:"Treatment Planning",topic:"Objectives",difficulty:2,profiles:["current","2027"],q:"Which is the BEST example of a measurable objective?",choices:["Client will feel better","Client will identify and practice two coping skills at least four days per week for the next month","Counselor will care deeply","Client will have no difficult emotions"],answer:1,why:"Objectives should be observable or measurable and tied to the larger goal.",rule:"OBJECTIVE = observable step + target."},
{id:17,domain:"Treatment Planning",topic:"Collaboration",difficulty:2,profiles:["current","2027"],q:"A counselor develops a technically sound plan that the client does not value. What is the main problem?",choices:["Nothing; the counselor is the expert","The plan lacks collaboration and may reduce engagement","The client should be discharged","All goals must come from a manual"],answer:1,why:"Effective treatment planning is collaborative and responsive to client goals, culture, strengths, and barriers.",rule:"A perfect plan the client won't use is not a perfect plan."},
{id:18,domain:"Treatment Planning",topic:"Level of care",difficulty:3,profiles:["current","2027"],q:"What should most strongly guide level-of-care decisions?",choices:["The counselor's convenience","Risk, functioning, clinical need, supports, and ability to remain safe at a less restrictive level","The client's diagnosis alone","Whether the program has an opening"],answer:1,why:"Level of care should reflect clinical need and safety, with attention to the least restrictive appropriate option.",rule:"LEVEL OF CARE = need + risk + functioning + supports."},
{id:19,domain:"Treatment Planning",topic:"Review",difficulty:2,profiles:["current","2027"],q:"A client has attended six sessions with little progress. What is the BEST next step?",choices:["Keep the same plan indefinitely","Review progress with the client and revise the formulation, goals, or interventions as indicated","Blame motivation","Terminate without discussion"],answer:1,why:"Treatment plans are living documents and should be revised based on response and new information.",rule:"NO PROGRESS → reassess before repeating."},
{id:20,domain:"Treatment Planning",topic:"Termination",difficulty:2,profiles:["current","2027"],q:"When counseling goals have largely been met, what is an appropriate focus?",choices:["Avoid discussing ending","Plan termination collaboratively, review gains, warning signs, resources, and follow-up needs","Create new problems to keep therapy going","End by text without discussion"],answer:1,why:"Planned termination consolidates progress and supports maintenance.",rule:"TERMINATION = review + relapse prevention + resources."},

{id:21,domain:"Counseling Skills & Interventions",topic:"Empathy",difficulty:1,profiles:["current","2027"],q:"Client: “I did everything right and still got rejected.” Which response best demonstrates empathic reflection?",choices:["“You shouldn't take it personally.”","“It sounds crushing to put that much into it and still hear no.”","“At least you tried.”","“Why didn't you apply somewhere else?”"],answer:1,why:"The response reflects the emotional meaning without minimizing, fixing, or interrogating.",rule:"EMPATHY names the experience before solving it."},
{id:22,domain:"Counseling Skills & Interventions",topic:"MI",difficulty:2,profiles:["current","2027"],q:"A client says, “Part of me wants to stop drinking, but it's the only way I relax.” Which response best fits motivational interviewing?",choices:["“You need to quit immediately.”","“What do you like about drinking, and what concerns you about it?”","“Alcohol is bad for you.”","“Let's ignore drinking and discuss childhood.”"],answer:1,why:"MI explores ambivalence and elicits the client's own reasons for change without confrontation.",rule:"MI = evoke, don't lecture."},
{id:23,domain:"Counseling Skills & Interventions",topic:"CBT",difficulty:2,profiles:["current","2027"],q:"Which intervention is most consistent with CBT?",choices:["Identify links among thoughts, feelings, and behavior and test unhelpful beliefs","Interpret every dream symbol","Avoid discussing behavior","Give advice without collaboration"],answer:0,why:"CBT examines relationships among cognition, emotion, and behavior and uses structured testing/practice.",rule:"CBT = notice pattern → test thought → practice behavior."},
{id:24,domain:"Counseling Skills & Interventions",topic:"Exposure",difficulty:3,profiles:["current","2027"],q:"A client with a phobia wants to overcome avoidance. Which approach is most consistent with evidence-based exposure principles?",choices:["Force the most feared situation without preparation","Collaboratively build graded practice with repeated contact and reduced avoidance/safety behaviors","Tell the client to avoid all triggers","Only discuss childhood causes"],answer:1,why:"Exposure is typically planned, collaborative, and repeated rather than coercive or purely avoidant.",rule:"EXPOSURE = planned approach, not forced flooding."},
{id:25,domain:"Counseling Skills & Interventions",topic:"Crisis",difficulty:3,profiles:["current","2027"],q:"A client is acutely overwhelmed after a crisis but can engage and is not in immediate danger. What is an appropriate early intervention?",choices:["Complex insight work","Stabilize, clarify immediate needs, mobilize supports, and create a concrete short-term plan","Assign a yearlong workbook","Challenge every cognitive distortion"],answer:1,why:"Early crisis work emphasizes stabilization, safety, practical needs, coping, and support.",rule:"CRISIS → stabilize first, deepen later."},
{id:26,domain:"Counseling Skills & Interventions",topic:"Psychoeducation",difficulty:1,profiles:["current","2027"],q:"What makes psychoeducation clinically useful?",choices:["It gives the client accurate, relevant information in a way they can understand and use","It replaces therapy","It proves the counselor is smarter","It should be delivered regardless of client interest"],answer:0,why:"Psychoeducation supports understanding and self-management when tailored to client needs.",rule:"Teach for USE, not for impressing."},
{id:27,domain:"Counseling Skills & Interventions",topic:"Family systems",difficulty:3,profiles:["current","2027"],q:"A counselor working systemically with a family is most likely to examine:",choices:["Only one person's symptoms in isolation","Interaction patterns, roles, boundaries, feedback loops, and context","Which family member is the villain","Only genetic factors"],answer:1,why:"Systemic work considers relational patterns and context rather than locating the whole problem in one person.",rule:"SYSTEMIC = pattern between people, not just symptom within person."},
{id:28,domain:"Counseling Skills & Interventions",topic:"Group",difficulty:2,profiles:["current","2027"],q:"In an early-stage counseling group, members are polite but cautious and look to the leader for structure. What is most helpful?",choices:["Demand deep confrontation immediately","Clarify purpose, norms, safety, and expectations while facilitating connection","Ignore confidentiality","Terminate the group"],answer:1,why:"Early groups benefit from structure, safety, norms, and cohesion-building.",rule:"EARLY GROUP = safety + structure + belonging."},

{id:29,domain:"Core Counseling Attributes",topic:"Positive regard",difficulty:1,profiles:["current","2027"],q:"Which response best reflects nonjudgmental positive regard?",choices:["“I agree with every choice you make.”","“I can respect you as a person while we examine whether this choice is working for you.”","“You should be ashamed.”","“I won't challenge anything you say.”"],answer:1,why:"Positive regard is respect for the person, not automatic endorsement of every behavior.",rule:"ACCEPT PERSON ≠ endorse every behavior."},
{id:30,domain:"Core Counseling Attributes",topic:"Cultural humility",difficulty:2,profiles:["current","2027"],q:"A client describes a cultural practice unfamiliar to the counselor. What is the BEST stance?",choices:["Assume the meaning based on a textbook","Ask respectful, open questions about what it means to this client","Avoid culture because it is uncomfortable","Explain the counselor's culture instead"],answer:1,why:"Cultural humility emphasizes curiosity, self-awareness, and the client's own meaning-making.",rule:"CULTURE → ask meaning; don't assign meaning."},
{id:31,domain:"Core Counseling Attributes",topic:"Congruence",difficulty:2,profiles:["current","2027"],q:"Counselor congruence is best described as:",choices:["Performing a professional persona that hides all reactions","Genuine, appropriate, and internally consistent presence","Sharing every personal detail","Always agreeing with the client"],answer:1,why:"Congruence reflects genuineness and consistency while preserving professional judgment and boundaries.",rule:"CONGRUENCE = real, not raw."},
{id:32,domain:"Core Counseling Attributes",topic:"Self-awareness",difficulty:3,profiles:["current","2027"],q:"A counselor notices unusually strong irritation toward a client. What is the BEST response?",choices:["Act on the irritation","Reflect on the reaction and use supervision/consultation as needed so it does not distort care","Tell the client they are annoying","Ignore it completely"],answer:1,why:"Counselor self-awareness helps identify reactions that may affect clinical judgment and the relationship.",rule:"YOUR REACTION = data, not a directive."},

{id:33,domain:"Areas of Clinical Focus",topic:"OCD",difficulty:2,profiles:["current","2027"],q:"Which pattern is most characteristic of obsessive-compulsive disorder?",choices:["Intrusive thoughts and/or repetitive behaviors performed to reduce distress or prevent a feared outcome","One panic attack","Chronic violation of others' rights","Elevated mood for four days"],answer:0,why:"OCD involves obsessions and/or compulsions that are time-consuming or impairing.",rule:"OCD = obsession/urge + compulsion/ritual loop."},
{id:34,domain:"Areas of Clinical Focus",topic:"PTSD",difficulty:3,profiles:["current","2027"],q:"Which cluster combination best fits PTSD assessment?",choices:["Trauma exposure plus intrusion, avoidance, negative mood/cognition changes, and arousal/reactivity symptoms","Sadness only","Fear only during public speaking","Compulsions without trauma"],answer:0,why:"PTSD assessment considers trauma exposure and symptoms across the major clusters, along with duration and impairment.",rule:"PTSD is a cluster pattern, not 'bad memory = PTSD.'"},
{id:35,domain:"Areas of Clinical Focus",topic:"Mania",difficulty:3,profiles:["current","2027"],q:"Which finding most strongly raises concern for a manic episode rather than ordinary happiness?",choices:["Feeling good after good news","Distinct period of elevated/irritable mood with increased energy, decreased need for sleep, and marked change in functioning","Enjoying social events","Sleeping eight hours"],answer:1,why:"Mania involves a distinct, clinically significant change in mood/energy and associated symptoms, not simply positive mood.",rule:"MANIA = distinct change + energy + symptoms + impairment/severity."},
{id:36,domain:"Areas of Clinical Focus",topic:"Psychosis",difficulty:2,profiles:["current","2027"],q:"A client reports hearing a voice. What should the counselor avoid assuming from that fact alone?",choices:["That further assessment is needed","That the client automatically has schizophrenia","That cultural and medical/substance context may matter","That risk should be assessed when relevant"],answer:1,why:"A hallucination is a symptom, not a diagnosis. Differential assessment includes context, course, substances, medical causes, mood disorders, trauma, and cultural factors.",rule:"SYMPTOM ≠ DIAGNOSIS."},
{id:37,domain:"Areas of Clinical Focus",topic:"Eating disorders",difficulty:3,profiles:["current","2027"],q:"A client with restrictive eating reports dizziness, fainting, and rapid weight loss. What is the clinical priority?",choices:["Body-image journaling only","Medical evaluation and level-of-care assessment alongside mental health treatment","Wait until the next routine visit","Focus only on family history"],answer:1,why:"Potential medical instability requires prompt medical assessment and appropriate level-of-care consideration.",rule:"MEDICAL INSTABILITY beats outpatient homework."},
{id:38,domain:"Areas of Clinical Focus",topic:"ADHD",difficulty:2,profiles:["current","2027"],q:"When assessing ADHD, why is information across settings useful?",choices:["Symptoms should be considered in more than one context and functional impairment matters","Teachers always diagnose ADHD","Parents cannot provide useful information","One setting is always enough"],answer:0,why:"ADHD assessment considers symptom patterns and impairment across contexts using multiple sources when appropriate.",rule:"ADHD → pattern across settings, not one rough Tuesday."},
{id:39,domain:"Professional Practice & Ethics",topic:"Court-ordered counseling",difficulty:3,profiles:["current","2027"],q:"A client is court-ordered to counseling. Which statement is most accurate as a general ethical principle?",choices:["The client loses all confidentiality rights","The counselor should clarify the limits of confidentiality, required reporting, and who will receive what information","All session content automatically goes to the court","Informed consent is unnecessary"],answer:1,why:"Court involvement changes some information-sharing requirements, but counselors still clarify roles, limits, and disclosures rather than assuming all rights disappear.",rule:"COURT-ORDERED ≠ no rights. Clarify the information pathway."},
{id:40,domain:"Counseling Skills & Interventions",topic:"Therapeutic rupture",difficulty:3,profiles:["current","2027"],q:"A client says, “You really didn't understand me last session.” What is the BEST response?",choices:["Defend the counselor's intent","Explore what felt misunderstood, acknowledge the impact, and work toward repair","Change the subject","Tell the client they are too sensitive"],answer:1,why:"Addressing ruptures directly and nondefensively can strengthen the alliance.",rule:"RUPTURE → curiosity + ownership + repair."}
];

const CASES = [
{
 id:"maya",icon:"🌪️",title:"Maya: Panic or Panic Disorder?",focus:"Assessment → diagnosis → treatment",
 intake:"Maya, 29, seeks counseling after an abrupt episode at a grocery store: pounding heart, sweating, trembling, chest tightness, dizziness, and fear she might faint. The episode peaked quickly. She has never had one before. Medical evaluation after the event was unremarkable.",
 steps:[
  {section:"INTAKE",q:"What is the most defensible conclusion right now?",choices:["Panic disorder","A panic attack occurred","Agoraphobia","Somatic symptom disorder"],answer:1,why:"One episode can establish a panic attack, but not necessarily panic disorder.",rule:"Episode first; disorder requires a pattern."},
  {section:"SESSION 1",add:"Over the next month, Maya has two more unexpected attacks. She spends most days worrying about another one and stops going to large stores.",q:"Which diagnosis is now more strongly supported?",choices:["Panic disorder","Specific phobia only","GAD","No disorder can ever be considered"],answer:0,why:"Recurrent unexpected panic attacks plus persistent concern/behavior change support panic disorder.",rule:"New timeline evidence changed the answer."},
  {section:"SESSION 2",add:"Maya wants to return to shopping and reduce fear of bodily sensations.",q:"Which treatment direction best matches the presentation?",choices:["CBT with psychoeducation and exposure-based work","Avoid all physical sensations","Supportive listening only forever","Immediate family therapy as the sole intervention"],answer:0,why:"CBT and exposure-based interventions are commonly used for panic symptoms and avoidance.",rule:"Treatment should target the mechanism maintaining the problem."}
 ]
},
{
 id:"darius",icon:"🧭",title:"Darius: Depression + Safety",focus:"Risk → level of care → collaborative plan",
 intake:"Darius, 41, reports six weeks of depressed mood, low energy, poor concentration, guilt, and sleep disruption after a divorce. He says, “Sometimes I think everyone would be better off without me.”",
 steps:[
  {section:"INTAKE",q:"What should happen NEXT?",choices:["Assume he is suicidal and hospitalize immediately","Complete a direct suicide risk assessment","Avoid the topic to preserve rapport","Start behavioral activation before asking anything else"],answer:1,why:"The statement warrants direct assessment before deciding intervention or level of care.",rule:"Safety signal → assess before escalating or minimizing."},
  {section:"SESSION 1",add:"Darius denies intent or plan, has no access to lethal means, identifies his children as strong reasons for living, agrees to a safety plan, and can use supports. He remains significantly depressed.",q:"What is the BEST planning stance?",choices:["Automatically inpatient","Continue clinically appropriate outpatient care with ongoing risk monitoring and a collaborative safety/treatment plan","Stop asking about suicide","Discharge him because he denied a plan"],answer:1,why:"Level of care depends on the whole risk picture, functioning, supports, and ability to remain safe.",rule:"Risk assessment guides level of care; one data point does not decide it."},
  {section:"SESSION 2",add:"After several sessions, Darius reports improved sleep and activity but persistent guilt and hopeless thoughts.",q:"Which intervention fits best?",choices:["CBT strategies targeting hopeless beliefs plus continued behavioral activation","Tell him to think positively","Avoid discussing cognition","Terminate because sleep improved"],answer:0,why:"The plan can build on gains while directly addressing remaining depressive processes.",rule:"Progress ≠ done; update the treatment target."}
 ]
},
{
 id:"riley",icon:"⚖️",title:"Riley: Ethics Under Pressure",focus:"Confidentiality → boundaries → consultation",
 intake:"Riley, 17, attends counseling with a parent involved in scheduling and payment. The parent calls after session demanding every detail Riley shared.",
 steps:[
  {section:"INTAKE",q:"What is the BEST ethical response?",choices:["Automatically provide every detail because the client is a minor","Clarify consent, confidentiality limits, applicable law/policy, and what information can appropriately be shared","Refuse to ever speak with the parent","End treatment"],answer:1,why:"Minor confidentiality is nuanced and depends on law, consent arrangements, clinical context, and safety. The counselor should clarify rather than assume.",rule:"LEGAL/ETHICAL nuance → clarify authority + limits before disclosing."},
  {section:"SESSION 1",add:"Riley asks the counselor to connect on a personal social media account so they can message anytime.",q:"What is the BEST response?",choices:["Accept because teens use social media","Maintain the boundary, review communication expectations, and explore what need the request represents","Block Riley without discussion","Create a secret second account"],answer:1,why:"Boundaries can be maintained while still exploring the client's underlying need for connection or access.",rule:"BOUNDARY + therapeutic exploration."},
  {section:"SESSION 2",add:"The counselor remains unsure about a state-specific rule affecting parental access to records.",q:"What is the BEST next step?",choices:["Guess","Consult appropriate supervision/legal-ethical resources before releasing information","Ask social media","Release the whole file to be safe"],answer:1,why:"When legal/ethical obligations are unclear, consultation is appropriate before action.",rule:"When the RULE is unclear, consult before disclosing."}
 ]
},
{
 id:"noah",icon:"🌀",title:"Noah: OCD Loop",focus:"Assessment → formulation → intervention",
 intake:"Noah, 24, reports intrusive thoughts that he may accidentally harm someone while driving. He finds the thoughts upsetting and repeatedly circles back to check roads even though he knows this is excessive.",
 steps:[
  {section:"INTAKE",q:"Which pattern is most consistent with the information provided?",choices:["OCD-type obsession/compulsion cycle","Antisocial personality disorder","Mania","Delirium"],answer:0,why:"The thoughts are intrusive and unwanted, and checking functions as a distress-reducing ritual.",rule:"Intrusive fear + ritualized neutralizing behavior = OCD loop to assess."},
  {section:"SESSION 1",add:"Noah spends two hours daily checking and has begun avoiding driving.",q:"Which functional question matters most for treatment planning?",choices:["How checking and avoidance maintain the cycle and impair daily life","His favorite color","Whether friends agree the fear is realistic","Whether he can promise never to feel anxious"],answer:0,why:"Treatment planning should target the mechanisms and impairment maintaining the problem.",rule:"Find what keeps the loop alive."},
  {section:"SESSION 2",add:"Noah is ready for structured treatment.",q:"Which intervention direction best fits?",choices:["Exposure with response prevention delivered competently and collaboratively","Increase checking until it feels perfect","Reassure him after every obsession","Avoid all driving permanently"],answer:0,why:"ERP is a core evidence-based treatment for OCD when delivered by a competent clinician.",rule:"OCD treatment targets avoidance + ritual reinforcement."}
 ]
}
];
